### ISSUE TITLE
How can I set default format for the new status map?

### ISSUE THREAD

**Issue by Langalf** [NagiosEnterprises/nagioscore#86] opened 2015-11-04 23:29 UTC
In Nagios Core 4.1.1 under Current Status, if I choose the (Legacy) status map it is possible to set a background image and a default user-supplied layout using the statusmap_background_image and default_statusmap_layout settings in cgi.cfg.

If I choose the Current Status > Map (the new status map) by default I get a Circular Balloon layout. I can access the Nagios Map menu and set "Layout: User Supplied" and "Dimensions: Fixed" and get an appearance similar to the legacy map except there is no place to set a background image. Also, there does not seem to be an option for saving those changes as a default setting for the Nagios Map.
 
Should there be a way to produce a Nagios Map with default settings of my choice?

**Comment by tmcnag** [comment] 2015-11-10 16:59
Workaround here:

https://support.nagios.com/forum/viewtopic.php?f=7&t=35476&p=160533#p160533

But basically, the new maps work well but do not yet have the same configuration capabilities as the old cgi-based maps, and will not respect the cgi.cfg settings at this time.

Digging further, this is a possible duplicate of https://github.com/NagiosEnterprises/nagioscore/issues/37 with my comment here https://github.com/NagiosEnterprises/nagioscore/issues/37#issuecomment-100604322.

I provided a workaround for the default layout there.

**Comment by Langalf** [comment] 2015-11-10 17:46
Thank you very much. These were exactly the workarounds I was looking for.

-------------------------------------------------------
Larry Schrupp <Larry.Schrupp@TalenEnergy.com>
Real Time Systems Administrator
Talen Energy - Colstrip Power Plant
P.O. Box 38, Colstrip, MT 59323-0038
office 406.748.5048; cell 406.740.0225

**Comment by jfrickson** [comment] 2015-12-03 20:53
Fixed by commit https://github.com/NagiosEnterprises/nagioscore/commit/d31e14613087b164529f905abf30034667f42689
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

**Closed by jfrickson** 2015-12-03 20:53 UTC
Labels: enhancement
