### ISSUE TITLE
Some recoveries are SOFT, but should've been HARD

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#651] opened 2019-06-14 19:17 UTC
There are some specific conditions, under which some services, recovering from a HARD CRITICAL state, go into a SOFT OK state. Therefore, recovery notifications are not sent.

The issue is described on the Nagios Support forum here:

https://support.nagios.com/forum/viewtopic.php?f=16&t=54293&p=285154#p285154

I was able to reproduce it in Nagios Core 4.4.3. The order of events is:

- Service goes to SOFT CRITICAL 1 of 3
- Service goes to SOFT CRITICAL 2 of 3
- Host goes DOWN
- Service goes to HARD CRITICAL 2 of 3
- Notification for the service is not sent as the host is still DOWN
- Host goes UP (recovers)
- Notification is sent for CRITICAL state the service 
- Service recovers to SOFT OK state (instead of HARD)
- Notification is NOT sent for the recovery of the service

Here's the relevant info from the nagios.log:

```
[Fri Jun 14 00:00:00 2019] CURRENT HOST STATE: CentOS-NRPE;UP;HARD;1;OK - 192.168.18.30: rta 0.172ms, lost 0%
[Fri Jun 14 13:19:26 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;1;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:19:46 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;2;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:20:50 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;3;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:21:10 2019] HOST ALERT: CentOS-NRPE;UP;SOFT;1;OK - 192.168.18.30: rta 0.116ms, lost 0%

[Fri Jun 14 13:17:30 2019] SERVICE ALERT: CentOS-NRPE;Users;CRITICAL;SOFT;1;USERS CRITICAL - 3 users currently logged in
[Fri Jun 14 13:18:27 2019] SERVICE ALERT: CentOS-NRPE;Users;CRITICAL;SOFT;2;USERS CRITICAL - 3 users currently logged in
[Fri Jun 14 13:19:26 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;1;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:19:46 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;2;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:20:25 2019] SERVICE ALERT: CentOS-NRPE;Users;CRITICAL;HARD;2;CHECK_NRPE STATE CRITICAL: Socket timeout after 59 seconds.
[Fri Jun 14 13:20:50 2019] HOST ALERT: CentOS-NRPE;DOWN;SOFT;3;CRITICAL - 192.168.18.30: rta nan, lost 100%
[Fri Jun 14 13:21:10 2019] HOST ALERT: CentOS-NRPE;UP;SOFT;1;OK - 192.168.18.30: rta 0.116ms, lost 0%
[Fri Jun 14 13:24:25 2019] SERVICE NOTIFICATION: nagiosadmin;CentOS-NRPE;Users;CRITICAL;xi_service_notification_handler;USERS CRITICAL - 3 users currently logged in
[Fri Jun 14 13:24:25 2019] SERVICE ALERT: CentOS-NRPE;Users;CRITICAL;HARD;2;USERS CRITICAL - 3 users currently logged in
[Fri Jun 14 13:29:24 2019] SERVICE ALERT: CentOS-NRPE;Users;OK;SOFT;2;USERS OK - 1 users currently logged in


```

**Comment by ericloyd** [comment] 2019-06-16 19:47
I think that may also be https://support.nagios.com/forum/viewtopic.php?f=16&t=52970, but I'm not sure that ever made it over here for tracking.

**Comment by Madlohe** [comment] 2019-06-16 20:58
@ericloyd take a look at #624 for that issue. The issue that @ludmilmm is describing is something that we can recreate on new Core machines, where the issue you linked here is something where we've only seen it on upgrades (at least internally).

**Comment by Madlohe** [comment] 2019-07-23 18:19
Working on this now; was able to reproduce on 4.4.3 and on maint. This is similar to #658

**Comment by Madlohe** [comment] 2019-07-23 19:48
I'm counting this as two separate issues. The first is that the service will get stuck as CRITICAL HARD x of y for x<y. For that, the offender seems to be 
https://github.com/NagiosEnterprises/nagioscore/blob/1c74fb9da693e4c6e3a72cb8b975b647518c4172/base/checks.c#L1345-L1354
And we can just add a line to adjust the current_attempt within that block.

(Note that the block is setting `state_type` and `new_last_hard_state` early, rather than using `service_state_or_hard_state_type_change()`, because that last function doesn't seem to work properly with the HOST DOWN => SERVICE CRITICAL logic.)

The second issue is that there should be a hard recovery after the service notification is sent out for a HARD non-OK state. After I made the change to fix the current attempt number, this seems to have resolved itself:

```
[1563911034] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;localhost;SSH;1563911033
[1563911034] SERVICE ALERT: localhost;SSH;CRITICAL;SOFT;1;SOMETHING: service has a status
[1563911041] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;localhost;SSH;1563911039
[1563911041] SERVICE ALERT: localhost;SSH;CRITICAL;SOFT;2;SOMETHING: service has a status
[1563911055] EXTERNAL COMMAND: SCHEDULE_FORCED_HOST_CHECK;localhost;1563911052
[1563911055] HOST ALERT: localhost;DOWN;SOFT;1;SOMETHING: host also has a status
[1563911068] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;localhost;SSH;1563911067
[1563911068] SERVICE ALERT: localhost;SSH;CRITICAL;HARD;3;SOMETHING: service has a status
[1563911096] EXTERNAL COMMAND: SCHEDULE_FORCED_HOST_CHECK;localhost;1563911095
[1563911096] HOST ALERT: localhost;UP;SOFT;1;SOMETHING: host also has a status
[1563911110] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;localhost;SSH;1563911108
[1563911110] SERVICE NOTIFICATION: nagiosadmin;localhost;SSH;CRITICAL;notify-service-by-email;SOMETHING: service has a status
[1563911126] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;localhost;SSH;1563911125
[1563911126] SERVICE NOTIFICATION: nagiosadmin;localhost;SSH;OK;notify-service-by-email;SOMETHING: service has a status
[1563911126] SERVICE ALERT: localhost;SSH;OK;HARD;3;SOMETHING: service has a status
```

At the end, we get alerted/notified for a HARD recovery (current attempt number gets reset after logging, which I believe is intended behavior).

**Comment by ericloyd** [comment] 2019-07-23 20:01
> 
> 
> @ericloyd take a look at #624 for that issue. The issue that @ludmilmm is describing is something that we can recreate on new Core machines, where the issue you linked here is something where we've only seen it on upgrades (at least internally).

I'll keep my mouth shut, then, and hope that 4.5 fixes EVERYTHING!! :-)

**Comment by Madlohe** [comment] 2019-07-23 20:19
No worries! I honestly get a lot of these issues confused myself.

Merged this into maint, closing.

**Closed by Madlohe** 2019-07-23 20:19 UTC
Labels: Bug
