### ISSUE TITLE
nagios 4.4.2 recovery notifications from UNREACHABLE/UNKNOWN for hosts/services are sent even if the contact didn't receive the UNREACHABLE/UNKNOWN notification

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#580] opened 2018-09-14 21:09 UTC
nagios 4.4.2 recovery notifications from UNREACHABLE/UNKNOWN for hosts or services are sent even if the contact didn't receive the UNREACHABLE/UNKNOWN notification (because they have UNREACHABLE/UNKNOWN notification option disabled). They still receive the recovery even though they didn't receive the UNREACHABLE/UNKNOWN notification, it shouldn't do this. It should only send the recovery if they received the problem. Works as it's supposed to with CRITICAL/WARNING.

Please see here for a more thorough explanation:

https://support.nagios.com/forum/viewtopic.php?f=16&t=50245

**Comment by scottwilkerson** [comment] 2018-09-19 15:47
I believe this is resolved in the maint branch after 5c984585d1ce9786c4b793c9f63b03a2a1740509

**Comment by jomann09** [comment] 2019-01-03 14:39
This is a duplicate of #584 which causes the notifications to be sent and the patch to that fixes this (no notifications means no recoveries sent)

**Comment by jomann09** [comment] 2019-01-03 16:39
This is fixed according to the forum post with the two commits @scottwilkerson made. Closing this, will be in Core 4.4.3.

**Closed by jomann09** 2019-01-03 16:39 UTC
Labels: Bug
