### ISSUE TITLE
Updating Nagios Package on CentOS 7 failing

### ISSUE THREAD

**Issue by nidhin215** [NagiosEnterprises/nagioscore#950] opened 2024-03-20 05:19 UTC
Unable to update packages in CentOS7/CL7 due to dependency issue

`--> Running transaction check
---> Package nagios-plugins-ssl_validity.x86_64 0:2.4.8-1.el7 will be installed
--> Processing Dependency: perl(Crypt::X509) for package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64
--> Processing Dependency: perl(Text::Glob) for package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64
--> Running transaction check
---> Package nagios-plugins-ssl_validity.x86_64 0:2.4.8-1.el7 will be installed
--> Processing Dependency: perl(Crypt::X509) for package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64
---> Package perl-Text-Glob.noarch 0:0.09-7.el7 will be installed
--> Finished Dependency Resolution
Error: Package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64 (epel)
           Requires: perl(Crypt::X509)
`

**Comment by gaguilard71** [comment] 2024-03-20 09:31
Are you tried to update using the update from the Nagios XI GUI?. If this is the case, because I ran in problems to update, first, be sure that the current configuration is ok, second, be sure that database repair process ends correctly, and after that, try to update manually following the instructions, taking on count that there are two different ways to perform it depending on the version you are trying to install. Try with a yum update and a reboot too before update. This was the only way that I had update Nagios to the last version. Cheers.

**Comment by nem8** [comment] 2024-03-20 21:09
Seeing the same issue when trying to update a RHEL 7 server:
---> Package nagios-plugins-ssl_validity.x86_64 0:2.4.8-1.el7 will be installed
--> Processing Dependency: perl(Crypt::X509) for package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64 (epel)
           Requires: perl(Crypt::X509)

**Comment by atdtinformatica** [comment] 2024-03-21 01:32
Since the new update, published on 03/18/24, of nagios in the epel repository (nagios core and plugins) this problem is occurring.

the problem is in an unsatisfied dependency for the package nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64

Here you can see the error:

# yum deplist nagios-plugins-ssl_validity-2.4.8-1.el7.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
  * base: centos.mirror.constant.com
  * epel: epel.mirror.constant.com
  * extras: mirrors.wcupa.edu
  * updates: centos.mirror.constant.com
package:nagios-plugins-ssl_validity.x86_64 2.4.8-1.el7
   dependency: /usr/bin/perl
    provider: perl.x86_64 4:5.16.3-299.el7_9
   dependency:nagios-plugins=2.4.8-1.el7
    provider: nagios-plugins.x86_64 2.4.8-1.el7
   dependency: openssl
    provider: openssl.x86_64 1:1.0.2k-26.el7_9
   **dependency: perl(Crypt::X509)
    Unsatisfied dependency**
   dependency: perl(Date::Format)
    provider: perl-TimeDate.noarch 1:2.30-2.el7
   dependency: perl(Date::Parse)
    provider: perl-TimeDate.noarch 1:2.30-2.el7
   dependency: perl(Digest::MD5)
    provider: perl-Digest-MD5.x86_64 2.52-3.el7
   dependency: perl(File::Basename)
    provider: webmin.noarch 2.014-1
    provider: perl.x86_64 4:5.16.3-299.el7_9
   dependency: perl(File::Temp)
    provider: perl-File-Temp.noarch 0.23.01-3.el7
   dependency: perl(Getopt::Long)
    provider: perl-Getopt-Long.noarch 2.40-3.el7
   dependency: perl(Getopt::Std)
    provider: perl.x86_64 4:5.16.3-299.el7_9
   dependency: perl(LWP::Simple)
    provider: perl-libwww-perl.noarch 6.05-2.el7
   dependency: perl(POSIX)
    provider: perl.x86_64 4:5.16.3-299.el7_9
   dependency: perl(Text::Glob)
    provider: perl-Text-Glob.noarch 0.09-7.el7

The package that provides the Crypt::X509 perl module is not correctly configured. As indicated in the deplist:

dependency: perl(Crypt::X509)
     Unsatisfied dependency

I hope you can report it to the corresponding person and it can be resolved as soon as possible.

Tnx,

Gabriel.-

**Comment by terryupton** [comment] 2024-03-21 08:15
I am also seeing the same errors.

**Comment by jouluz** [comment] 2024-03-21 11:14
https://bugzilla.redhat.com/show_bug.cgi?id=2270251

Here is the reason

**Comment by UftangForgeTech** [comment] 2024-03-21 22:44
Also there is no other version in the repo now. So the installation on the clean Centos 7 vm will fail as well.
`yum --showduplicates list  nagios-plugins-all
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
 * base: download.cf.centos.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
Available Packages
nagios-plugins-all.x86_64                                                                                                      2.3.3-2.el7                                                                                                       epel`

**Comment by francescor** [comment] 2024-03-25 07:26
we are stuck, too

installing `perl-Crypt-OpenSSL-X509.x86_64` does not solve

**Comment by Wade9320** [comment] 2024-03-25 17:04
We are having the same issue too.

**Comment by nidhin215** [comment] 2024-03-26 04:22
Hi

I was able to fix it by running the below command

` yum-config-manager --enable epel-testing  && yum update -y`

**Comment by iphoster** [comment] 2024-03-26 05:16
> Hi
> 
> I was able to fix it by running the below command
> 
> ` yum-config-manager --enable epel-testing && yum update -y`

it doesn't give any result

**Comment by vmpr** [comment] 2024-03-26 05:23
> Hi
> 
> I was able to fix it by running the below command
> 
> ` yum-config-manager --enable epel-testing && yum update -y`

that's not a good idea to just enable the epel-testing repo, all the packages in there are in testing state, so you will probably start to install unstable packages into your system

**Comment by francescor** [comment] 2024-03-26 07:51
we are stuck with *all* our production Centos 7, a viable solution would be I guess to disable the `nagios-plugins-all` while installing (selecting, one by one) all its plugins but `nagios-plugins-ssl_validity` (any ideas on how to do it easily?), and installing it back when this issue is solved (btw, we would really like to have  `nagios-plugins-ssl_validity`, so we're very happy it's coming)

**Comment by nidhin215** [comment] 2024-03-26 15:22
> we are stuck with _all_ our production Centos 7, a viable solution would be I guess to disable the `nagios-plugins-all` while installing (selecting, one by one) all its plugins but `nagios-plugins-ssl_validity` (any ideas on how to do it easily?), and installing it back when this issue is solved (btw, we would really like to have `nagios-plugins-ssl_validity`, so we're very happy it's coming)

You can disable the nagios updates for now by adding it to the exclude section in /etc/yum.conf

**Comment by rmaslanka** [comment] 2024-03-26 15:32
I suppose the issue was fixed today:
https://bugzilla.redhat.com/show_bug.cgi?id=2270251#c4

**Comment by francescor** [comment] 2024-03-26 18:14
We confirm, too, it's solved now

**Comment by sawolf** [comment] 2024-04-03 15:48
Hi @francescor - I think `nagios-plugins-ssl_validity` is probably [this perl script](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_ssl_validity.pl). I'm not familiar with the EPEL packages but I wouldn't be too surprised if it was rolled into the main package (or a nagios-plugins perl package if that exists).

It sounds like the original issue is resolved now; closing.

**Closed by sawolf** 2024-04-03 15:48 UTC
Labels: Question
