### ISSUE TITLE
Feature Request:: Possibility to Mark Unreachable Service as Unknown

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#283] opened 2016-10-04 15:35 UTC
Currently, if a host goes down, services are left in the state before the host went down. An Unknown status would be more clear, particularly for those that are not familiar with the organizations service-host architecture.

Since this would be a substantial change to the current Nagios workflow for down hosts, it is suggested that this functionality turned on at the discretion of the user.

Additional details at https://support.nagios.com/forum/viewtopic.php?f=7&t=40229.

**Comment by jfrickson** [comment] 2017-03-13 18:37
This didn't make it for 4.3.0. I'll see about getting it implemented in 4.4.0.

**Comment by jfrickson** [comment] 2017-05-17 21:52
This is actually a duplicate of issue #229

**Closed by jfrickson** 2017-05-17 21:52 UTC
Labels: duplicate, enhancement
