### ISSUE TITLE
Status map in 4.1 rc1 doubled host with more parents

### ISSUE THREAD

**Issue by pozda2** [NagiosEnterprises/nagioscore#34] opened 2015-03-31 14:26 UTC
Hi

I have host with two parents in my test nagios configuration. 

define host {
  hostname a
}

define host {
hostname b
parents a
}

define host {
hostname c
parents a,b
}

define host {
hostname d
parents c
}

There were two lines from host c in previous version of Nagios.
New version of status map displays host c (with his child d) two times. The graph of network is now confusing.

Pozda

**Comment by tmcnag** [comment] 2015-06-16 03:44
Confirmed behavior in 4.1.0rc1:

![Parent Map](https://i.imgur.com/RBhHVh8.png)

**Comment by joseaguardia** [comment] 2015-12-15 15:15
Same issue here.

config:

define host{
use host-no-critico,host-pnp

host_name helpdesk_svrsistemas

alias App helpdesk en svrsistemas
parents apache_svrsistemas,mysql_svrsistemas
icon_image website256.png
statusmap_image website.gd2
address 192.168.1.222
}
![nagios_map_legacy](https://cloud.githubusercontent.com/assets/16305835/11814411/e17985a8-a346-11e5-9f80-89aca24d8bf7.png)
![nagios_map_new](https://cloud.githubusercontent.com/assets/16305835/11814412/e1819fa4-a346-11e5-9b15-e831d46299be.png)

**Comment by thinkitdata** [comment] 2016-08-25 15:20
I see this issue still exists in v4.2.0.  Is there anything in the works to fix this?

**Comment by jfrickson** [comment] 2016-08-25 16:14
Unfortunately, we're using D3 to produce the map, and D3 doesn't support multiple parents. So this probably won't get resolved until either D3 does, or we get something else to produce the map.

**Comment by thinkitdata** [comment] 2016-08-25 16:58
That's cool, thanks for the heads up.

**Comment by hedenface** [comment] 2017-06-18 20:44
I'm going to close the issue on here, since there are several open that are similar - this will be fixed in 5.

**Closed by hedenface** 2017-06-18 20:44 UTC
Labels: Bug, Duplicate
