### ISSUE TITLE
Event Broker Module not unloaded on program restart.

### ISSUE THREAD

**Issue by seeingninths** [NagiosEnterprises/nagioscore#583] opened 2018-09-27 14:39 UTC
I have a really simple base module that I'm testing...

/*****************************************************************************
*
* Compile with the following command:
*
*     gcc -shared -o base-modulue base-module.c -fPIC
*
*****************************************************************************/

#include <nagioscore/include/nebmodules.h>
#include <nagioscore/include/nebcallbacks.h>
#include <nagioscore/include/nebstructs.h>

NEB_API_VERSION(CURRENT_NEB_API_VERSION);

int nebmodule_init(int flags, char *args, nebmodule *handle)
{
	//save our handle
	//module_handle = handle;

	write_to_all_logs("Init.", NSLOG_INFO_MESSAGE);
	return 0;
}

int nebmodule_deinit(int flags, int reason)
{
	write_to_all_logs("Deinit.", NSLOG_INFO_MESSAGE);
	return 0;
}

The module is loaded by Nagios Core with no issues.  When I restart the process from system -> process info -> Restart the Nagios Process the module isn't unloaded, but it IS reloaded.  Then when shutting the Nagios process down, the deinit method is called the number of times the process has been restarted + 1.  Below are the logs.

Informational Message[09-27-2018 10:31:55] Event broker module '/usr/local/nagios/broker-modules/base-module' deinitialized successfully.
Informational Message[09-27-2018 10:31:55] RDeinit.
Informational Message[09-27-2018 10:31:55] Event broker module '/usr/local/nagios/broker-modules/base-module' deinitialized successfully.
Informational Message[09-27-2018 10:31:55] RDeinit.
Informational Message[09-27-2018 10:31:55] Event broker module '/usr/local/nagios/broker-modules/base-module' deinitialized successfully.
Informational Message[09-27-2018 10:31:55] RDeinit.
Informational Message[09-27-2018 10:31:55] Successfully shutdown... (PID=2397)
Program End[09-27-2018 10:31:55] PROGRAM_SHUTDOWN event encountered, shutting down...
External Command[09-27-2018 10:31:55] EXTERNAL COMMAND: SHUTDOWN_PROCESS;1538058715
Informational Message[09-27-2018 10:31:51] Event broker module '/usr/local/nagios/broker-modules/base-module' initialized successfully.
Informational Message[09-27-2018 10:31:51] Init.
Informational Message[09-27-2018 10:31:51] wproc: Registry request: name=Core Worker 2424;pid=2424
Informational Message[09-27-2018 10:31:51] wproc: Registry request: name=Core Worker 2423;pid=2423
Informational Message[09-27-2018 10:31:51] wproc: Registry request: name=Core Worker 2422;pid=2422
Informational Message[09-27-2018 10:31:51] wproc: Registry request: name=Core Worker 2421;pid=2421
Informational Message[09-27-2018 10:31:51] wproc: Successfully registered manager as @wproc with query handler
Informational Message[09-27-2018 10:31:51] qh: help for the query handler registered
Informational Message[09-27-2018 10:31:51] qh: echo service query handler registered
Informational Message[09-27-2018 10:31:51] qh: core query handler registered
Informational Message[09-27-2018 10:31:51] qh: Socket '/usr/local/nagios/var/rw/nagios.qh' successfully initialized
Informational Message[09-27-2018 10:31:51] LOG VERSION: 2.0
Informational Message[09-27-2018 10:31:51] Local time is Thu Sep 27 10:31:51 EDT 2018
Program Start[09-27-2018 10:31:51] Nagios 4.4.1 starting... (PID=2397)
Program Restart[09-27-2018 10:31:51] PROGRAM_RESTART event encountered, restarting...
External Command[09-27-2018 10:31:51] EXTERNAL COMMAND: RESTART_PROCESS;1538058711
Informational Message[09-27-2018 10:31:43] Event broker module '/usr/local/nagios/broker-modules/base-module' initialized successfully.
Informational Message[09-27-2018 10:31:43] Init.
Informational Message[09-27-2018 10:31:43] wproc: Registry request: name=Core Worker 2414;pid=2414
Informational Message[09-27-2018 10:31:43] wproc: Registry request: name=Core Worker 2413;pid=2413
Informational Message[09-27-2018 10:31:43] wproc: Registry request: name=Core Worker 2412;pid=2412
Informational Message[09-27-2018 10:31:43] wproc: Registry request: name=Core Worker 2411;pid=2411
Informational Message[09-27-2018 10:31:43] wproc: Successfully registered manager as @wproc with query handler
Informational Message[09-27-2018 10:31:43] qh: help for the query handler registered
Informational Message[09-27-2018 10:31:43] qh: echo service query handler registered
Informational Message[09-27-2018 10:31:43] qh: core query handler registered
Informational Message[09-27-2018 10:31:43] qh: Socket '/usr/local/nagios/var/rw/nagios.qh' successfully initialized
Informational Message[09-27-2018 10:31:43] LOG VERSION: 2.0
Informational Message[09-27-2018 10:31:43] Local time is Thu Sep 27 10:31:43 EDT 2018
Program Start[09-27-2018 10:31:43] Nagios 4.4.1 starting... (PID=2397)
Program Restart[09-27-2018 10:31:43] PROGRAM_RESTART event encountered, restarting...
External Command[09-27-2018 10:31:43] EXTERNAL COMMAND: RESTART_PROCESS;1538058703
Informational Message[09-27-2018 10:31:11] Successfully launched command file worker with pid 2403
Informational Message[09-27-2018 10:31:11] Event broker module '/usr/local/nagios/broker-modules/base-module' initialized successfully.
Informational Message[09-27-2018 10:31:11] Init.
Informational Message[09-27-2018 10:31:11] wproc: Registry request: name=Core Worker 2400;pid=2400
Informational Message[09-27-2018 10:31:11] wproc: Registry request: name=Core Worker 2399;pid=2399
Informational Message[09-27-2018 10:31:11] wproc: Registry request: name=Core Worker 2402;pid=2402
Informational Message[09-27-2018 10:31:11] wproc: Registry request: name=Core Worker 2401;pid=2401
Informational Message[09-27-2018 10:31:11] wproc: Successfully registered manager as @wproc with query handler
Informational Message[09-27-2018 10:31:11] qh: help for the query handler registered
Informational Message[09-27-2018 10:31:11] qh: echo service query handler registered
Informational Message[09-27-2018 10:31:11] qh: core query handler registered
Informational Message[09-27-2018 10:31:11] qh: Socket '/usr/local/nagios/var/rw/nagios.qh' successfully initialized
Informational Message[09-27-2018 10:31:11] LOG VERSION: 2.0
Informational Message[09-27-2018 10:31:11] Local time is Thu Sep 27 10:31:11 EDT 2018
Program Start[09-27-2018 10:31:11] Nagios 4.4.1 starting... (PID=2397)

CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)

Nagios Core 4.4.1
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2018-06-25
License: GPL

Let me know what other information I can provide.  Thanks.

**Comment by dvoryanchikov** [comment] 2018-10-08 09:46
Hi, @seeingninths ,
You can use my patch to base/nagios.c from #573 !

**Comment by jomann09** [comment] 2019-01-14 17:12
Duplicate of #573 and should be in the next release.

**Closed by jomann09** 2019-01-14 17:12 UTC
Labels: Duplicate
