### ISSUE TITLE
Double Map in Nagios Core

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#578] opened 2018-09-06 16:57 UTC
The issue has been reported on the Nagios Core support forum here:

[https://support.nagios.com/forum/viewtopic.php?t=50123#261387](url)

I was able to recreate the issue in Nagios Core 4.4.2 as well.

**Comment by scottwilkerson** [comment] 2018-09-06 18:48
Closing, duplicate of #471

**Closed by scottwilkerson** 2018-09-06 18:48 UTC
