### ISSUE TITLE
Offline installation hits infinite loop issue on startup

### ISSUE THREAD

**Issue by HunnyPuns** [NagiosEnterprises/nagioscore#953] opened 2024-03-28 18:22 UTC
User reported issue
https://support.nagios.com/forum/viewtopic.php?p=356170#p356170

Apparently if Nagios Core cannot reach the internet, when it starts up, it will continuously loop over the updates check. Will chew up 100% of 1 CPU core while attempting to get to the internet.

Temporary work around:
Set `check_for_updates=0` in `/usr/local/nagios/etc/nagios.cfg`

Edit:
Nagios Core version 4.5.1
Linux distro is likely Debian or Ubuntu, based on the `www-data` user rather than `httpd` user.

Tested against Nagios Core version 4.4.13 (with Nagios XI) on Debian 11, by removing the default gateway, and did not run into the issue.

**Comment by sawolf** [comment] 2024-04-01 16:37
Probably duplicate of #927, but this summary is more accurate. Will try to get this one fixed for next release.

**Comment by sawolf** [comment] 2024-04-01 17:31
Just kidding! I missed the last sentence on your report. I'm also not able to repro this behavior, even after matching his setup steps.  Even if I break w/ gdb and turn on the firewall in the middle of the communication, I'm not able to get an infinite loop.

**Closed** 2024-09-25 17:03 UTC
Labels: Bug
