### ISSUE TITLE
Bug: Nagios 4.4.5 Service checks are not running properly and Nagios alerts are not sent, Nagios Core is getting struck & 

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#748] opened 2020-03-17 03:27 UTC
We use Nagios core to monitor our Infrastructure. we have like 207 hosts and 967 services configured which include cpu load,disk, memory and other custom script to monitor backups and logfiles and other things. 
What I have observed from last couple of days is Nagios is unable to handle all the service checks. I'll give you example of 1 service check we configured for monitoring our backups. We have jenkins running and we backups of jenkins every night. So we have script in nagios which checks for backup status from a API response for a success string in the response every day in the morning around 9 and is performed only 1 check for a day. This check was not performed from march 13th. So I have observed and restarted the Nagios. but the nagios service next check shows as march 17, before nagios restart it was showing as march 14th. 

I'm guessing Nagios was struck performing service checks.  It was unable to perform any checks on any service for last two days. MArch 14th & march 15th NAgios was hung, but I was able to view NAgios UI and everything. Nagios Restart fixed it. I'll update this ticket If I see this issue again. 
![Nagios-error](https://user-images.githubusercontent.com/48814564/76819049-94cb3480-67dd-11ea-85db-a1931bf2ca5c.PNG)

I have checked the log directory of nagios /usr/local/nagios/var/archives/ and I don't see any logs of nagios-03-15-2020-00.log and after nagios restart a log file created with today's(march 16th)date. 

-rw-r--r--. 1 nagios nagios  18M Mar 12 22:37 nagios-03-11-2020-00.log
-rw-r--r--. 1 nagios nagios  19M Mar 13 23:59 nagios-03-14-2020-00.log
-rw-r--r--. 1 nagios nagios  19M Mar 16 23:08 nagios-03-13-2020-00.log 

I'm adding a screenshot for example of a service. Let me know if you need more information.

**Comment by sawolf** [comment] 2020-03-18 14:44
Hi @rosri1992, thanks for reporting this.

How is the system doing in terms of hardware requirements (free disk space/RAM/CPU load)? I haven't seen something like this happen, but I know linux tends to act strangely when any of these are exhausted.

**Comment by rosri1992** [comment] 2020-03-18 14:51
Hi,

Our Nagios Instance is provisioned in AWS with m4.2xlarge. That Instance is only used for Nagios.  We don't have any other applications running on that Instance. 

free -h command output 
              total        used        free      shared  buff/cache   available
Mem:            31G        2.8G        995M        1.6G         27G         26G
Swap:            0B          0B          0B
uptime output
 10:50:15 up 25 days, 43 min,  1 user,  load average: 0.35, 0.34, 0.26

Let me know if you need more information.

Thanks,
Srikanth

**Comment by sawolf** [comment] 2020-03-20 14:26
Hi,

Thanks for sharing that. A couple of questions:

1.) Can you share your disk usage? Out of the three things I mentioned this is the most likely to cause problems.

2.) Are you sure nothing else is running? If I remember correctly, Nagios Core should be well under 1GB, so even 3GB of RAM usage is surprising on a system that has ~1200 monitored objects.

**Comment by rosri1992** [comment] 2020-03-23 21:49
Hi,

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda2       80G   30G   51G  38% /

This is our root partition which is being used by Nagios process. 

Yes,  Nagios is the only process running on the instance. 

Let me know if you need more information
Thanks,
Srikanth

**Comment by rosri1992** [comment] 2020-03-26 16:37
I can send you the screenshot of top command but I can't because of company's regulations.

**Comment by sawolf** [comment] 2020-03-26 16:42
Good to know.

Is this issue ongoing for you? It isn't clear from reading this over whether restarting nagios resolved the problem or not (or whether it fixes it for awhile, then the problem restarts).

**Comment by rosri1992** [comment] 2020-03-31 16:57
Hey

We are seeing different issues with alerts. When we trigger custom alerts we are able to get them, but we nagios tries to schedule a alert we are getting them. we have integrated those alerts with Slack channel. I have observed this in event log of Nagios 
![image](https://user-images.githubusercontent.com/48814564/78053765-10d18a80-734f-11ea-91d3-4a5165b8c91c.png) I'm seeing a lot of wproc kills :( It's a Urgent request. let me know if you need more information

**Comment by rosri1992** [comment] 2020-03-31 17:25
@sawolf 

Also Can check this screenshot too. I have seen this in /var/log/messages file repeatedly.

![image](https://user-images.githubusercontent.com/48814564/78056406-14671080-7353-11ea-8c9f-428a3fe97c27.png)

**Comment by sawolf** [comment] 2020-04-01 19:54
At this point I think that the issues are likely caused by either the checks or the notification script you have set up. The errors you're showing so far indicate that the jobs (so either checks or notifications) are timing out, rather than a problem with core itself.

What exactly are you doing when you "trigger custom alerts"? Do you mean that you're running the notification handler from the terminal? Personally, I would recommend setting up a script that can give you some debugging output, e.g.:

```
#!/bin/bash

echo $@ >> /tmp/args.log
```

and replacing the slack integration with this temporarily. This will allow you to make sure that you're running the notification handler with the same arguments that are causing errors in nagios core.

**Comment by rosri1992** [comment] 2020-04-16 21:32
Slack Integration is nothing but sending an alert to slack channel instead to my email. That slack channel has a email app integrated and gave us email id. we are using that email id to send alerts to slack channel.

Can we focus on why this is happening in our nagios core set up.
![image](https://user-images.githubusercontent.com/48814564/79508790-3970aa00-8008-11ea-998c-836c99f1def3.png)

**Comment by ericloyd** [comment] 2020-04-16 21:53
The problem is exactly what it says - it's taking too long to process your service check and so it's killing it to prevent runaway zombie processes.  @sawolf is making a suggestion that will obtain more debugging information, but you're welcome to skip that step.

The bigger question is why is your service check taking so long?  My suggestion for getting assistance with that is that it's not a Nagios code issue but something else, and should be asked in the Nagios support forums, not in the Nagios Core Git repo.

Check out https://support.nagios.com/forum/index.php and look for the Community Support forum.

**Comment by rosri1992** [comment] 2020-04-16 22:00
We have configured few hosts(CISCO Switches& routers  Hosts) and we have few bash scripts in plugins directory, these scripts has a ssh step where ssh will be performed to that CISCO host and few commands will be executed and output of that command is logged in to file in Nagios server. The same script checks the log file if the command output is same as expected output of the script then Nagios throws OK status. If not it throws Critical or Warning alerts. So  I think NAgios can't ssh into few hosts that is why it is killing the zombie process. 

We are working on the how to get ssh working for Nagios for those CISCO hosts.

**Comment by ericloyd** [comment] 2020-04-16 22:04
By default, you have 60 seconds to complete a Nagios service checks.  If it takes longer than that, Nagios will kill it.  You might want to have this check be performed in multiples phases, each phase of which can be checked independently.  One that does the SSH command and a separate one that checks the log file, maybe?  Nagios is certainly capable of SSHing into a host, executing commands, capturing the output, and then seeing what the results were, but it has to do it all in 60 seconds or less.

Again, you may want to take this to the support forum for more widespread assistance.

**Comment by sawolf** [comment] 2020-04-17 15:11
That's a fair point, @ericloyd. I assumed that the script is running in under a minute normally and that something is causing it to hang when it's running from Core. Maybe I should have clarified that before asking for full debug information.

@rosri1992, I agree with Eric - Core is definitely able to use ssh by default. It may be possible that you (or someone in your org) configured your system so that nagios can't SSH, but there's no way for us to know about that. 
If it is the case that your command is taking longer than 60 seconds to execute, you'll either need to figure out some way to make it faster, or you can increase the notification_timeout in nagios.cfg so that it's above the normal running time.

**Closed** 2024-09-20 14:56 UTC
