### ISSUE TITLE
csv output in html code

### ISSUE THREAD

**Issue by tjyang** [NagiosEnterprises/nagioscore#570] opened 2018-08-04 15:58 UTC
Hi
Please fix the csv output function to strip out all html code.
Following is from  4.4.1 avail.cg

![image](https://user-images.githubusercontent.com/378638/43678225-128e991e-97d5-11e8-8446-7028f786273f.png)

**Comment by tjyang** [comment] 2018-08-06 17:16
* With "&csvoutput=" specified and output with text"Content-type: text/csv" but the code section of creating csv format not reached.

```
me@nagios02 contrib]$ cat 39.bash
#!/usr/bin/bash
REMOTE_USER=nagiosadmin \
REQUEST_METHOD=GET \
QUERY_STRING="\
show_log_entries=&hostgroup=linux-servers\
&timeperiod=last7days\
&smon=12\
&sday=1\
&syear=2018\
&shour=0\
&smin=0\
&ssec=0\
&emon=12\
&eday=31\
&eyear=2018\
&ehour=24\
&emin=0\
&esec=0\
&rpttimeperiod=&assumeinitialstates=yes\
&assumestateretention=yes\
&assumestatesduringnotrunning=yes\
&includesoftstates=no\
&initialassumedhoststate=3\
&initialassumedservicestate=6\
&backtrack=4\
&csvoutput=" \
 gdb  ./rpmbuild/BUILD/nagios-4.4.1/cgi/avail.cgi
[me@nagios02 contrib]$ ./39.bash
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later 
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
...
Reading symbols from /home/me/nagioscore.my/contrib/rpmbuild/BUILD/nagios-4.4.1/cgi/avail.cgi...done.
(gdb) run
Starting program: /home/me/nagioscore.my/contrib/./rpmbuild/BUILD/nagios-4.4.1/cgi/avail.cgi
Cache-Control: no-store
Pragma: no-cache
Last-Modified: Sat, 04 Aug 2018 22:20:53 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-type: text/csv
Content-Disposition: attachment; filename="avail.csv"

<BR><BR>
<DIV ALIGN=CENTER CLASS='dataTitle'>Hostgroup 'linux-servers' Host State Breakdowns:</DIV>
<DIV ALIGN=CENTER>
<TABLE BORDER=0 CLASS='data'>
<TR><TH CLASS='data'>Host</TH><TH CLASS='data'>% Time Up</TH><TH CLASS='data'>% Time Down</TH><TH CLASS='data'>% Time Unreachable</TH><TH CLASS='data'>% Time Undetermined</TH></TR>
<tr CLASS='dataOdd'><td CLASS='dataOdd'><a href='avail.cgi?host=localhost&show_log_entries&t1=1532816453&t2=1533421253&backtrack=4&assumestateretention=yes&assumeinitialstates=yes&assumestatesduringnotrunning=yes&initialassumedhoststate=3&initialassumedservicestate=6&show_log_entries&showscheduleddowntime=yes'>localhost</a></td><td CLASS='hostUP'>95.094% (95.094%)</td><td CLASS='hostDOWN'>4.906% (4.906%)</td><td CLASS='hostUNREACHABLE'>0.000% (0.000%)</td><td class='dataOdd'>0.000%</td></tr>
<tr CLASS='dataEven'><td CLASS='dataEven'>Average</td><td CLASS='hostUP'>95.094% (95.094%)</td><td CLASS='hostDOWN'>4.906% (4.906%)</td><td CLASS='hostUNREACHABLE'>0.000% (0.000%)</td><td class='dataEven'>0.000%</td></tr></table>
</DIV>
[Inferior 1 (process 19784) exited normally]
(gdb)
```

**Comment by hedenface** [comment] 2018-08-07 19:15
I am unable to reproduce

**Comment by hedenface** [comment] 2018-08-08 15:07
@cdienger was able to reproduce, so I will attempt to fix. Thanks.

**Comment by hedenface** [comment] 2018-08-08 21:16
fixed via https://github.com/NagiosEnterprises/nagioscore/commit/2d6467d6600b4ac44781e7011b9b80d7c58749c4 and https://github.com/NagiosEnterprises/nagioscore/commit/cccb20f7769639658ff42b2e94ff87d47e53923d

**Closed by hedenface** 2018-08-08 21:16 UTC
Labels: Bug

**Comment by tjyang** [comment] 2018-08-17 10:59
@hedenface 

Thanks for the fix, following is my confirmation using same "39.bash" script.

```
[tjyang@nagios02 contrib]$ ./39.bash
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/tjyang/nagioscore/contrib/rpmbuild/BUILD/nagios-4.4.2/cgi/avail.cgi...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/tjyang/nagioscore/contrib/./rpmbuild/BUILD/nagios-4.4.2/cgi/avail.cgi
Cache-Control: no-store
Pragma: no-cache
Last-Modified: Fri, 17 Aug 2018 10:56:28 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-type: text/csv
Content-Disposition: attachment; filename="avail.csv"

HOSTGROUP_NAME, HOST_NAME, TIME_UP, PERCENT_TIME_UP, PERCENT_KNOWN_TIME_UP, TIME_DOWN, PERCENT_TIME_DOWN, PERCENT_KNOWN_TIME_DOWN, TIME_UNREACHABLE, PERCENT_TIME_UNREACHABLE, PERCENT_KNOWN_TIME_UNREACHABLE, TIME_UNDETERMINED, PERCENT_TIME_UNDETERMINED
"linux-servers", "localhost", 0, 0.000%, 0.000%, 604800, 100.000%, 100.000%, 0, 0.000%, 0.000%, 0, 0.000%
[Inferior 1 (process 15976) exited normally]
(gdb)
```
