### ISSUE TITLE
"View Status" links under "Map" broken in Nagios Core Version 4.1.1

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#76] opened 2015-08-24 21:28 UTC
None of the links under "Map->Network Map for All Hosts" is working.

To recreate the issue - click on "Map", then click on any of the links under "Network Map for All Hosts":

- View Status Detail For This Host
- View Status Detail For All Hosts
- View Status Overview For All Hosts

You will see "404 Not Found" error.

```
The requested URL /nagios/status.cgi was not found on this server.
```
For more info, see the following post on the Nagios Support forum:

https://support.nagios.com/forum/viewtopic.php?f=7&t=34334&p=149852

**Comment by box293** [comment] 2015-08-25 05:01
The problem is in the map-links.html file

Instead of:
```
status.cgi
```
it should be 
```
cgi-bin/status.cgi
```
On lines 6, 11, 15

**Comment by wh1test** [comment] 2015-08-25 07:56
I think in 4.1.1 something wrong in cgi paths. Why 4.1.1 search cgi files for map/trends/histograms in /var/www/cgi-bin and not search in /usr/local/nagios/sbin ?
The previous releases don't have this behavior.

**Comment by jfrickson** [comment] 2015-08-25 14:21
The new maps are done with Angular and D3. The `<addr>`{params.cgiurl}`</addr>` variable probably points to the directory where the Angular app (`<addr>`map.html`</addr>`) lives.

I'm guessing the correct fix would be to set an appropriate Angular variable, but I don't know Angular. The quick fix would be to add the `<addr>`cgi-bin/.`</addr>` before the `<addr>`status.cgi`</addr>` as Troy suggested. Unless someone dissents, I'll do the quick fix.

**Comment by jfrickson** [comment] 2015-08-25 17:29
Fixed with commit:
https://github.com/NagiosEnterprises/nagioscore/commit/c1eac72b2041648d9c9be74480d078a8b6bf9513
in branch:
https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-beta

**Closed by jfrickson** 2015-08-25 17:29 UTC
