### ISSUE TITLE
check_http warning after upgrade 4.4.5

### ISSUE THREAD

**Issue by trentasis** [NagiosEnterprises/nagioscore#732] opened 2020-02-13 10:58 UTC
Hi,

Recently I have updated nagios 4.0.8 to 4.4.5

After this I have detected that all chekc_http are showing warning alert, and command used is the same with nagios 4.0.8

Executing command from cli show OK and value is right, but from cfg same command show warning 

CLI
 /usr/local/nagios/libexec/check_http -S -H server.domain.local -u "/Osc.jsp" -p 8443 -s "Coding" -w 0,5 -c 3
HTTP OK: HTTP/1.1 200 OK - 4686 bytes in 0,075 second response time |time=0,074912s;0,500000;3,000000;0,000000 size=4686B;;;0

webinterface
url: server.domain.local
This service has 1 comment associated with it	This service is flapping between states	Perform Extra Service Actions
WARNING	02-13-2020 11:51:25	0d 0h 4m 39s	3/3	HTTP WARNING: HTTP/1.1 200 OK - 354 bytes in 0.415 second response time 

I tried to remove -w and -c and then works, but without alerts... 

also tried to update angios-plugins from 2.0.3 to 2.1.3 but error persist, and error has appeared after nagios update 4.4.5

Nagios and nagios-plugins updated with 2 steps and error reproduced after nagios update

Any suggestion how to sovle this issue?

Thanks

**Comment by sawolf** [comment] 2020-02-13 15:14
When you say that you updated to 2.1.3, did you mean 2.3.1? 2.1.3 is many years old at this point.

Otherwise, I suspect that your issue isn't nagios so much as the network between nagios and whatever you're trying to monitor. If I'm reading correctly, the service in nagios is flapping, which means that it's sometimes coming out OK and sometimes showing warning. Looking between your commands, there's also a large variation between response times on any given check.

**Comment by trentasis** [comment] 2020-02-13 16:55
Sorry, right 2.3.1

Is not flapping, warning is defined as 0.5s, and error has appewred on all check http services 180, at same time afyer upgrade nagios 4.0.8 to 4.4.5

Nagios plugin update was updated afternagios update and no difference on results

Check http from cli works but same command on cfg shpwnwarning alert, what is the difference and why has appeared since 4.4.5 update?

Thanks

**Comment by sawolf** [comment] 2020-02-13 19:07
Okay, that makes more sense. I didn't realize that you had only upgraded Nagios Core by the time you started seeing the errors. 

Unfortunately, I haven't seen an issue like this come up before, and the upgrade from 4.0.8 to 4.4.5 represents 5-6 years of changes. At this point, I would recommend reverting the upgrade, and upgrading to an earlier release (e.g. 4.2.4 or 4.3.4) to see if you still have the same issue on that version. We can narrow the root cause from there.

**Comment by trentasis** [comment] 2020-02-13 20:11
Hi, first, thanks for yout information!

I have upgrade to 
4.2.4 -->OK
4.3.4 -->OK
4.4.0 -->OK
4.4.1 -->OK
4.4.2 -->OK
4.4.3 -->OK
4.4.4 -->OK
4.4.5 -->OK

It seems that with some steps works... strange?

**Comment by sawolf** [comment] 2020-02-13 20:19
I agree, that's really bizarre. It's not *that* unusual for incremental upgrades to work better for most software, but that's usually from changing something that's "outside" of the normal source code (e.g. a database schema, or a change in a file hierarchy). I can't think of anything like that which would exist for Nagios Core.

Regardless, as long as this solved you're issue, I'm going to close this issue. If it comes up again, either comment here or open a new issue and we'll look into it then.

**Comment by trentasis** [comment] 2020-02-13 20:24
Thanks, one last question from 4.0.8 to 4.4.5 what other additiconal change are neede, I have complied from sources, any other action required?

**Comment by sawolf** [comment] 2020-02-13 20:48
As far as I'm aware, nagios configuration should be backward compatible from 4.4.x to 4.0.x. Just make sure to keep any changes you've made to your .cfg files.

If you have any 3rd-party integrations that you're running (pnp4nagios, mod_gearman, etc), make sure that those are on versions that are compatible with your current version of nagios as well.

**Comment by trentasis** [comment] 2020-02-13 20:56
What do you know abput init file and webconf described here
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html

**Comment by sawolf** [comment] 2020-02-13 21:50
I hadn't seen those notices before. Thanks for pointing that out to me.

I don't know exactly what changes occurred there, but you can probably follow those directions if you haven't already.

**Comment by trentasis** [comment] 2020-02-13 22:07
Thanks!

**Comment by trentasis** [comment] 2020-02-18 11:23
Hi,

It seems that error persist, and I have found that after install is working but when I make a service nagios stop and then service nagios start error appears on all check_http.
I have found, that if I reboot centos, then check are working until we reboot machine


Any suggestio how to debug this issue?

Thanks

**Comment by trentasis** [comment] 2020-02-18 11:43
Hi @sawolf 
additional info, upgraded using:

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html

making init and lockfile change described 

Please can you reopen issue? how can -I debug to understand after a full reboot OS works and nagios restart and reload no?

thanks

**Comment by trentasis** [comment] 2020-02-18 14:25
I have made some tests, and seems error related with new initfile, but I can't knowwhere is the issue, any suggestion?

**Comment by sawolf** [comment] 2020-02-18 16:16
Hi @trentasis, 

Sorry to hear that your problems have continued.

It seems like the main change with the init file was that the lockfile's location changed. First, I'd check that the `NagiosRunFile` directive in the init file is the same as the `lock_file` directive in your nagios.cfg.

If you've done this and the problems continue, I'd make sure that the lock file exists and that nagios has permission to read/write to it.

If the permissions look okay and nagios continues to have issues after restart, then we can turn on debugging. You should be able to set `debug_level` to 16 to enable debugging for check logic, `debug_verbosity` to 2, and `debug_file` to `/usr/local/nagios/var/nagios.debug`. Then restart nagios again and post the log after you've had some checks process.

**Comment by trentasis** [comment] 2020-02-19 11:26
Hi @sawolf 

NagiosRunfile and lock_file with correct values:
# cat /etc/init.d/nagios |grep NagiosRunFile
NagiosRunFile=/var/run/nagios.lock
# cat /usr/local/nagios/etc/nagios.cfg |grep lock_file
lock_file=/var/run/nagios.lock

About permissions detected this 
nagios 4.4.5
ls -lisah /var/run/nagios.lock
5243687 4,0K -rw-r--r-- 1 root root 5 feb 19 11:24 /var/run/nagios.lock
nagios 4.0.8
# ls -lisah /usr/local/nagios/var/nagios.lock
3947434 0 -rw-r--r-- 1 nagios nagios 0 feb 18 13:15 /usr/local/nagios/var/nagios.lock

It seems that with 4.4.5 user nagios has no permissions added chown like was in 4.0.8 and now works
after this 
                su $NagiosUser -c "touch $NagiosVarDir/nagios.log $NagiosRetentionFile"
                /bin/rm -f $NagiosCommandFile
                touch $NagiosRunFile
                chown $NagiosUser:$NagiosGroup $NagiosRunFile
                $NagiosBin -d $NagiosCfgFile


And now 
# ls -lisah /var/run/nagios.lock
5244135 4,0K -rw-r--r-- 1 nagios nagios 5 feb 19 12:24 /var/run/nagios.lock

and all working!

Anybody can validate and add this change if all is OK, I have checked that in nagios 4.0.8, multiple chown were in initfile, but with 4.4.5 any chown is in the file

Thanks

**Comment by trentasis** [comment] 2020-02-19 12:26
issue reproduced  with permission, now I'll try to enalbe debug...

**Comment by trentasis** [comment] 2020-02-19 14:23
nagiosdebug output:

[1582121649.946368] [016.2] [pid=11311] Processing check result for service 'url: 3m.hosppal.es' on host '3m'
[1582121649.946397] [016.0] [pid=11311] ** Handling ACTIVE async check result for service 'url: 3m.hosppal.es' on host '3m' from 'Core Worker 11317'... current state 1 last_hard_state 1
[1582121649.946406] [016.1] [pid=11311]  * OPTIONS: 1, SCHEDULED: 1, RESCHEDULE: 1, EXITED OK: 1, RETURN CODE: 1, OUTPUT:
HTTP WARNING: HTTP/1.1 200 OK - 4687 bytes in 0.121 second response time |time=0.120685s;0.000000;3.000000;0.000000 size=4687B;;;0

[1582121649.946428] [016.2] [pid=11311] Parsing check output...
Short Output: HTTP WARNING: HTTP/1.1 200 OK - 4687 bytes in 0.121 second response time
Long Output: NULL
Perf Data:      time=0.120685s;0.000000;3.000000;0.000000 size=4687B;;;0
[1582121649.946441] [016.1] [pid=11311] Service is in a non-OK state!
[1582121649.946448] [016.1] [pid=11311] Host is currently UP, so we'll recheck its state to make sure...
[1582121649.946454] [016.2] [pid=11311] Service not ok, host is up, using cached host data
[1582121649.946462] [016.1] [pid=11311] Service was NOT OK at last check (WARNING).
[1582121649.946471] [016.1] [pid=11311] Service is still in a non-OK state (WARNING)!
[1582121649.946478] [016.2] [pid=11311] Service state type is hard, sending a notification
[1582121649.946484] [016.1] [pid=11311] Checking service 'url: 3m.hosppal.es' on host '3m' for flapping...
[1582121649.946502] [016.2] [pid=11311] LFT=5.00, HFT=20.00, CPC=20.00, PSC=20.00%
[1582121649.946516] [016.1] [pid=11311] Service is flapping (20.00% state change).
[1582121649.946525] [016.1] [pid=11311] Checking host '3m' for flapping...
[1582121649.946533] [016.2] [pid=11311] LFT=5.00, HFT=20.00, CPC=0.00, PSC=0.00%
[1582121649.946542] [016.1] [pid=11311] Host is not flapping (0.00% state change).
[1582121649.946564] [016.1] [pid=11311] Rescheduling next check of service at Wed Feb 19 15:19:09 2020
[1582121649.946602] [016.0] [pid=11311] Scheduling a non-forced, active check of service 'url: 3m.hosppal.es' on host '3m' @ Wed Feb 19 15:19:09 2020
[1582121649.946612] [016.2] [pid=11311] Scheduling new service check event.


If you need I can obtain and send by mail more information

Im not understanding why after os reboot works, and after service nagios restart fails, with nagios.lock permissions right (user nagios) 

Any idea?

Thanks

**Comment by sawolf** [comment] 2020-02-19 16:00
I made a mistake here - it's fine for root:root to own /var/run/nagios.lock. 

Are you sure the problem is related to your init file? i.e., if you:
- use your init file from 4.0.8, 
- use Core 4.4.5, 
- make a configuration change (add a new service), and 
- restart nagios core via the init file
The issue is fixed for you?

I am interested in seeing more of the debugging output. Feel free to send the debug log in an attachment to swolf@nagios.com. I'll also set up a test instance to see if I can reproduce the issue.

**Comment by trentasis** [comment] 2020-02-20 10:56
Hi,

I have made some additional test step by step using https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html:

-snapshot revert to 4.0.8
-update to nagios 4.4.5
- restart using init 4.0.8, works!
- restart after add a service using init 4.0.8, works!
- make httpd changes, restart and all working
- make init changes (make install-init & cahnge lock_file on nagios.cfg to /var/run/nagios.lock) --> after this change, if you make service restart nagios then error is reproduced

If at this situation you copy you old initfile and change lock_file to old path /usr/local/nagios/var/nagios.lock

tried to use initfile 4.4.5 with /usr/local/nagios/var/nagios.lock but then appears an error, in this situation using /usr/local/nagios/var/nagios.lock with 4.0.8 initfile and nagios core 4.4.5 no working..

I am little confused, error warning only occurs with one command check_http described in previous messages, and from cli check output ok, but nagios shows warning, very strange

Tested on two environment, 350hosts and 4500services and 200hosts and 2000 services

**Comment by trentasis** [comment] 2020-02-20 11:57
added init file form 4.0.8 and 4.4.5

**Comment by trentasis** [comment] 2020-02-25 11:19
hi,

Until we have this issue solved, we have applied a workaround that allows to works correctly,

service nagios stop
replace nagios lock_file  on nagios.cfg
#lock_file=/var/run/nagios.lock
lock_file=/usr/local/nagios/var/nagios.lock

revert init file from 4.4.5 to 4.0.8
cd /etc/init.d
 cp nagios408 nagios

With this after service nagios restart all check are showing values correctly, also check_http that was showing a bad alert (warning) using init 4.4.5

thanks

**Comment by sawolf** [comment] 2020-02-25 15:29
Thanks for the update. 

If changing the init file reduces check duration for you, then I think we'll leave it at that. Those two systems aren't supposed to be related in any way and I haven't seen this behavior in any other users' environments.

**Closed by sawolf** 2020-02-25 15:29 UTC
Labels: Bug, Need Information

**Comment by trentasis** [comment] 2020-02-26 08:42
Hi, sorry, but I don't really understand because issue was clased, we only applied a workaround, It will be great to keep open to be solved on future versions.

Thanks

**Comment by sawolf** [comment] 2020-02-26 17:44
Hi. Maybe I haven't explained this well enough.

I really think nagios is working as expected, and that there is (or was) an issue with the network and/or website that you're monitoring. `check_http` (or any other nagios plugin) runs as an isolated program, impacted only by the arguments you send to it. These arguments are specified in the nagios configuration (the files and directories specified in `nagios.cfg`), not by the init file. Changing the lock file, especially, would not have an impact on the check duration itself. It could have an impact on the daemon's own startup, but this wouldn't impact how checks run afterwards. 

If you want to prove this to yourself, try running `ps -ef | grep nagios` once nagios is running with the 4.0.8 init file and with the 4.4.5 init file. You shouldn't see a difference between the arguments that are used to start nagios. 

Independently of that, we've already ruled out that updated plugins could be causing the issue, or that the Nagios Core source could be causing the issue (since we had the same issues or resolution of issues with plugins 2.0.3 and 2.3.1, and with Core 4.0.8 and 4.4.5). That's why I'm calling this issue resolved.
