### ISSUE TITLE
default-init (classic init, daemon-init) based systems cannot restart correctly

### ISSUE THREAD

**Issue by beckit** [NagiosEnterprises/nagioscore#480] opened 2018-02-09 08:57 UTC
I noticed that the daemon-init (and now default-init) script has a bug.

It stems from here, where instead of the pid being written to the runtime file, the runtime file just gets a touch -
https://github.com/NagiosEnterprises/nagioscore/blob/master/startup/default-init.in#L220

This causes the subsequent call in pid_nagios() to have no actual pid to fill in -
https://github.com/NagiosEnterprises/nagioscore/blob/master/startup/default-init.in#L166

As such, the restart routine never has a chance to actually kill the right nagios process, so nothing gets restarted.   

To make the bug "worse", once a restart is issued, due to the touch logic and effectively broken pid_nagios(), another nagios can startup when others are running.

**Comment by beckit** [comment] 2018-02-09 09:19
I'm working on a fix.  I have one for the classic daemon-init, but the new default-init has a few extra wrinkle.

**Comment by box293** [comment] 2018-02-09 13:10
Check out this pull request as I've fixed a few init issues while testing the upcoming 4.4.0 release.

https://github.com/NagiosEnterprises/nagioscore/pull/470

**Comment by hedenface** [comment] 2018-02-15 14:08
Any updates on whether @box293 's fixes resolved your issues, @beckit ?

**Comment by hedenface** [comment] 2018-02-16 12:49
Also @beckit, what operating system are you running on? What version of Nagios are you using? Did you install via packages or compile from source? If from source, can you provide what steps you took for the installation, or a link to the documentation you followed?

**Comment by hedenface** [comment] 2018-02-17 14:39
> It stems from here, where instead of the pid being written to the runtime file, the runtime file just gets a touch -
> https://github.com/NagiosEnterprises/nagioscore/blob/master/startup/default-init.in#L220

This is because the daemon itself writes to the pid file before dropping privileges.

> This causes the subsequent call in pid_nagios() to have no actual pid to fill in -
> https://github.com/NagiosEnterprises/nagioscore/blob/master/startup/default-init.in#L166

I am not able to replicate this behavior. 

Although there are some issues that this has brought up, while doing some testing on cent6 boxes. I'm getting a 1 in 5 restart error (out of every 5 tries, 1 of them hangs indefinitely) - but the pid file has the appropriate pid each time - I'll investigate further, but any additional information you could provide could potentially be very useful, @beckit. Thanks.

**Comment by beckit** [comment] 2018-02-17 19:47
I have a fix, I need more time to integrate your new default-init changes.  I've identified the bug, you're close.  Will post findings, details and integrated fix pull request this weekend in theory.

**Comment by hedenface** [comment] 2018-02-18 03:49
I actually would like to say that I think this is a much larger bug than just the init file, based on my investigation today. If I had to wager a guess, it'd be related to the fix for #441 - at least this is what it looks like to me now.

**Comment by hedenface** [comment] 2018-02-18 03:55
On a whim, I decided to test my method (not using the init script, but rather a `kill -s HUP [pid]` from the command line) on a systemd based server, and got about the same 1 in 5 chance of some craziness occuring during the restart.

To hopefully add some helpful info: I added a bunch of output (and ran the nagios command from the command line to see the logfile printed to the screen as it's running) in between the sigchld handling, and then after the execution is returned to the main event loop. So in between each major function being called once the `sigrestart = TRUE` ....and ..there is no correlation. It doesn't always stop in the same place. But again, this is completely without the fix I mentioned previously - which needs some fixing up of it's own.

**Comment by hedenface** [comment] 2018-02-18 04:58
Also, the darndest thing - I can't get my problem to reproduce when I enable debugging symbols for gcc - before I did that, I was seeing some deadlock possibilities though, on both mint and centos6 - so hopefully this is a start.

I also really hope the bug you rose as an issue is actually related to the one I'm seeing - otherwise my apologies for hijacking your thread :)

**Comment by ccztux** [comment] 2018-02-18 16:04
With the actual build of the master branch the restart issue still occurs.

**Comment by beckit** [comment] 2018-02-19 09:35
I'm working out a pull request - for now I'm leaving it in my maint branch:
https://github.com/beckit/nagioscore/commit/9fdbc448d0bec69690b5ef667520cfe7c6e313ba

root cause of the bugs:
instead of calculating the nagios pid and echoing it to a file,
the file was simply touched and left empty.  Other functions depend
on the pid being in the file.

there seems to be a catch-22/race condition in that /var/run/nagios has
to exist for nagios to run correctly.
touch $NagiosRunFile

needs to change to this call:
echo $NagiosPID > $NagiosRunFile


fixes several minor bugs:

stops and restarts can happen because the pid can be determined,
where "kill" needs that pid.

nagios reports weird kill help when running "service nagios stop" on sysv init

moved the echo after a configuration check, so that the output
from the echo doesnt get clobbered (Starting nagios:Running...) and the
"done" has a chance of aligning

fixes up contrib/daemonchk.cgi, which relies on /var/run/nagios having a pid
in it

avoided using awk. while tempting, it adds installation heavyness.  The
WARN and ERR usage of awk and sed in check_config() should be cleaned
up, but this checkin focuses on the pid calculation and handling elsewhere.


my script fixes enable this to be seen:
theres a bug if nagios is started and then suddenly stopped,
not sure where its hanging up, but it will hit this race condition, where
teh SIGTERM is caught before all of the workers are up:
[1519026938] wproc: Successfully registered manager as @wproc with query handler
[1519026938] wproc: Registry request: name=Core Worker 2079;pid=2079
[1519026938] wproc: Registry request: name=Core Worker 2083;pid=2083
[1519026938] wproc: Registry request: name=Core Worker 2080;pid=2080
[1519026938] wproc: Registry request: name=Core Worker 2082;pid=2082
[1519026940] Caught SIGTERM, shutting down...
[1519026942] Successfully launched command file worker with pid 2106

I've not determined what fix is appropriate, a simple sleep seems
like it could "work" as an interim fix, but doesn't feel "right",
as it penalizes shutting down stable systems. 

I will file a seperate bug for the startup/shutdown race condition

**Comment by beckit** [comment] 2018-04-09 18:31
the pull request is waiting on maint to catch up to main and a little bit on me to look into solving issue #487

**Comment by hedenface** [comment] 2018-06-15 22:59
I believe this issue is fixed with the latest pushes to the init script. If someone is still able to replicate, please either re-open this issue or open a new one. Thanks.

**Closed by hedenface** 2018-06-15 22:59 UTC
Labels: Bug, Code Quality
