### ISSUE TITLE
Nagios Core 4.1.1 - workers seemingly dont notice check completion

### ISSUE THREAD

**Issue by iscb2015** [NagiosEnterprises/nagioscore#84] opened 2015-10-23 06:55 UTC
Nagios Core 4.1.1 built from source on Solaris 11.2 (SPARC).
No options supplied to configure script.
Configuration following sample, only real change is the directory with configuration information.

When running the following style messages are logged (repeatedly) to the nagios.log (in a 60 second period there are between 500 and 900 messages logged depending on check activity)

[1445582254] wproc: Core Worker 14747: job 49765 (pid=21636) timed out. Killing it
[1445582254] wproc: Core Worker 14747: job 49765 with pid 21636 reaped at timeout. timeouts=49747; started=49789

Large number (averages around 400) of defunct processes which are children of the nagios and nagios worker processes.

Web interface reports that the run time for all (all the ones I've looked at - see also nagiostat output below) service and host checks are just over 60 and 30 seconds respectively which matches the maximum times for the checks defined in the nagios configuration.

Checks seem to be working - although they're taking longer to report the information.

# /usr/local/nagios/bin/nagiostats

Nagios Stats 4.1.1
Copyright (c) 2003-2008 Ethan Galstad (www.nagios.org)
Last Modified: 08-19-2015
License: GPL

CURRENT STATUS DATA
------------------------------------------------------
Status File:                            /usr/local/nagios/var/status.dat
Status File Age:                        0d 0h 0m 8s
Status File Version:                    4.1.1

Program Running Time:                   0d 22h 37m 20s
Nagios PID:                             14744

Total Services:                         1427
Services Checked:                       1424
Services Scheduled:                     1394
Services Actively Checked:              1427
Services Passively Checked:             0
Total Service State Change:             0.000 / 6.120 / 0.004 %
Active Service Latency:                 0.000 / 30.377 / 0.078 sec
Active Service Execution Time:          0.000 / 60.093 / 58.653 sec
Active Service State Change:            0.000 / 6.120 / 0.004 %
Active Services Last 1/5/15/60 min:     0 / 1020 / 1392 / 1392
Passive Service Latency:                0.000 / 0.000 / 0.000 sec
Passive Service State Change:           0.000 / 0.000 / 0.000 %
Passive Services Last 1/5/15/60 min:    0 / 0 / 0 / 0
Services Ok/Warn/Unk/Crit:              1398 / 8 / 4 / 17
Services Flapping:                      0
Services In Downtime:                   0

Total Hosts:                            302
Hosts Checked:                          302
Hosts Scheduled:                        294
Hosts Actively Checked:                 302
Host Passively Checked:                 0
Total Host State Change:                0.000 / 0.000 / 0.000 %
Active Host Latency:                    0.000 / 2025.389 / 20.777 sec
Active Host Execution Time:             4.056 / 30.089 / 29.323 sec
Active Host State Change:               0.000 / 0.000 / 0.000 %
Active Hosts Last 1/5/15/60 min:        11 / 227 / 294 / 294
Passive Host Latency:                   0.000 / 0.000 / 0.000 sec
Passive Host State Change:              0.000 / 0.000 / 0.000 %
Passive Hosts Last 1/5/15/60 min:       0 / 0 / 0 / 0
Hosts Up/Down/Unreach:                  301 / 1 / 0
Hosts Flapping:                         0
Hosts In Downtime:                      1

Active Host Checks Last 1/5/15 min:     45 / 277 / 834
   Scheduled:                           45 / 277 / 834
   On-demand:                           0 / 0 / 0
   Parallel:                            45 / 277 / 834
   Serial:                              0 / 0 / 0
   Cached:                              0 / 0 / 0
Passive Host Checks Last 1/5/15 min:    0 / 0 / 0
Active Service Checks Last 1/5/15 min:  305 / 1374 / 4158
   Scheduled:                           305 / 1374 / 4158
   On-demand:                           0 / 0 / 0
   Cached:                              0 / 0 / 0
Passive Service Checks Last 1/5/15 min: 0 / 0 / 0

External Commands Last 1/5/15 min:      0 / 0 / 0

I found the bug documented at https://tracker.nagios.org/view.php?id=498 which reports the same error messages and I tried to recompile using the io-broker option that was documented as fixing the issue there - however the configure option --with-ibroker=epoll is reported as not available.

I have tried rebuilding using configure --with-iobroker=select which gets rid of the timeout messages, but results in the following style messages 

[1445496380] wproc: 'Core Worker 14436' seems to be choked. ret = -1; bufsize = 142: errno = 11 (Resource temporarily unavailable)
[1445496380] Unable to run check for service 'service name' on host 'hostname'

and no checks seem to work.

When attempting to compile after using configure --disable-event-broker the compile fails - last few lines of compilation shown below;

gmake[2]: Leaving directory `/var/tmp/ian/nagios-4.1.1/lib'
gcc -Wall -I.. -I /usr/include -I /usr/include/gd2 -DHAVE_CONFIG_H -DNSCORE -o nagios nagios.o  ../common/shared.o nerd.o query-handler.o workers.o checks.o config.o commands.o events.o flapping.o logging.o macros-base.o netutils.o notifications.o sehandlers.o utils.o retention-base.o xretention-base.o comments-base.o xcomments-base.o objects-base.o xobjects-base.o statusdata-base.o xstatusdata-base.o perfdata-base.o xperfdata-base.o downtime-base.o    -lm -lsocket  -lsocket  ../lib/libnagios.a
Undefined                       first referenced
 symbol                             in file
neb_free_module_list                nagios.o
neb_register_callback               nerd.o
neb_deregister_callback             nerd.o
neb_add_core_module                 nerd.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
gmake[1]: *** [nagios] Error 1
gmake[1]: Leaving directory `/var/tmp/ian/nagios-4.1.1/base'
gmake: *** [all] Error 2

**Comment by tmcnag** [comment] 2015-11-04 20:55
Can you please provide some architecture information? OS, version, 32- vs 64-bit, etc.

**Comment by iscb2015** [comment] 2015-11-05 07:38
I'm not sure what extra you require - it says on the first line of the entry "Solaris 11.2 (SPARC)".
Solaris has been (AFAIK) 64 bit (on SPARC) for many years.

Please let me know if there is other information you require.

Thanks

Ian

**Comment by giteric** [comment] 2015-11-05 13:36
I'm guessing @tmcnag missed that.  I'm guessing the next question will be "can you post the contents of your configure.log" file.

**Comment by iscb2015** [comment] 2015-11-05 13:41
Which one ?
                The one where the workers perform the checks but don’t pick up the results until the timeout expires
                Or the one where the workers do not perform the checks.

I’m on holiday until 16th Nov after today and I probably will not get chance to post all the info today – if not I will do so shortly after I get back. Let me know if there is any other info required.

Thanks

Ian

**Comment by giteric** [comment] 2015-11-05 14:42
It says on the very second line: "No options supplied to configure script."  :-)

I'm looking for the configure.log file from the compile that you did.

**Comment by tmcnag** [comment] 2015-11-05 15:00
Yea, sorry about that.  I was replying to quite a few issues in a row and I mistook this issue for this one:  https://github.com/NagiosEnterprises/nagioscore/issues/85#issuecomment-153862321

Similar green icons + lack of sleep = Not doing anyone any good  :)

**Comment by iscb2015** [comment] 2015-12-01 11:34
Apologies for taking so long to response with the log file.

Ian
[config-log.txt](https://github.com/NagiosEnterprises/nagioscore/files/48446/config-log.txt)

**Comment by pziental** [comment] 2016-04-19 13:25
Hi,
any updates with this problem?

I have the same OS and also nagios was comliped from sources.
I saw at nagios.debug that the killed process is starting...

################
[1461067685.024907] [008.0] [pid=2489] ** Service Check Event ==> Host: 'localhost', Service: 'Current Users', Options: 0, Latency: 0.000000 sec
[1461067685.024939] [001.0] [pid=2489] run_scheduled_service_check() start
[1461067685.024974] [016.0] [pid=2489] Attempting to run scheduled check of service 'Current Users' on host 'localhost': check options=0, latency=0.000000
################

and after 60 seconds:

################
[1461067745.033323] [016.0] [pid=2489] ** Handling check result for service 'Current Users' on host 'localhost' from 'Core Worker 2493'...
[1461067745.033364] [016.1] [pid=2489] HOST: localhost, SERVICE: Current Users, CHECK TYPE: Active, OPTIONS: 0, SCHEDULED: Yes, RESCHEDULE: Yes, EXITED OK: Yes, RETURN CODE: 0, OUTPUT: USERS OK - 6 users currently logged in |users=6;20;50;0
################

is pushing same error.

Grettings,
Piotr

**Comment by Semirben** [comment] 2016-07-29 11:48
Hi,

same result for me on Solaris 11.3 (Both i386 and SPARC). 
```
dheitepriem@s26:~$ uname -a
SunOS s26 5.11 11.3 i86pc i386 i86pc
dheitepriem@s26:~$ cat /etc/release 
                             Oracle Solaris 11.3 X86
  Copyright (c) 1983, 2015, Oracle and/or its affiliates.  All rights reserved.
                            Assembled 06 October 2015
```
I compiled Nagios 64-bit using
```
CFLAGS="-m64" LDFLAGS="-m64" CXXFLAGS="-m64" ./configure --prefix=/opt/nagios
[...]
CFLAGS="-m64" LDFLAGS="-m64" CXXFLAGS="-m64" /usr/bin/gmake all
[...]
/usr/bin/gmake install
```
The output of nagios.log
```
[1469792820] wproc: Core Worker 22418: job 10549 (pid=26568) timed out. Killing it
[1469792820] wproc: Core Worker 22418: job 10549 with pid 26568 reaped at timeout. timeouts=10549; started=10551
###
ps -ef | grep 26568
  nagios 26568 22418   0        - ?           0:00 <defunct>
```
Regards,
Daniel Heitepriem

**Comment by jfrickson** [comment] 2016-10-18 15:17
There were a couple of changes recently for problems that mainly effected Solaris. These are now in the 'maint' branch (https://github.com/NagiosEnterprises/nagioscore/tree/maint). Can some or all of you test and see if those changes have resolved this problem?

**Comment by Semirben** [comment] 2016-10-19 09:43
The problem is solved over here (Solaris 11.3 SPARC). No more 'defunct' processes and also no "timed out" warnings in nagios.log

```
# ps -ef | grep nagios | wc -l
      45
# ps -ef | grep nagios | grep defunct| wc -l
```

**Comment by jfrickson** [comment] 2016-10-19 14:04
Great news! I'm closing the issue, but if anyone still has problems, please reopen it.

**Closed by jfrickson** 2016-10-19 14:04 UTC
Labels: bug

**Comment by Semirben** [comment] 2016-10-20 10:31
Hmm, it doesn't seems to be solved entirely. After deploying the maint-build to a Solaris 11 i386 machine with more checks and therefore more throughput, the "defunct" processes reappeared
```
# ps -ef | grep nagios | grep defunct | wc -l 
      36
# ps -ef | grep nagios | grep -v defunct | wc -l
      27
```
```
# tail -f /logs/nagios/nagios.log
[1476959276] wproc: Core Worker 29991: job 7 (pid=3769) timed out. Killing it
[1476959276] wproc: Core Worker 29991: job 7 with pid 3769 reaped at timeout. timeouts=7; started=8
```
But they get at least killed without any issues:
```
# ps -ef | grep 3769
# ps -ef | grep 29991
nagios 29991 29980   0 12:16:10 ?           0:00 /opt/nagios/bin/nagios --worker /opt/nagios/var/rw/nagios.qh
#
```
