### ISSUE TITLE
  Creating Service groups with host groups

### ISSUE THREAD

**Issue by throwsb** [NagiosEnterprises/nagioscore#98] opened 2015-12-09 18:16 UTC
Hi,

I opened Topic on the Nagios XI page regarding Creating Service Groups. viewtopic.php?f=16&t=36038 I wanted to see if I can add a feature. I went to github and it seemed to point me back to here. Let me know if this is not the right place for feature comments.

I currently have the situation where we have 75+ production, QA, .. application servers that have host checks as well as Weblogic Checks. It is common to have large maintenance windows where the application is shutdown for hours or more. When that happens, the checks start alerting. The only way around is to put all services for that group into maintenance mode. That means we loose the health of the servers, which we need.

A great feature to add to Core is a way to create a service group that will allow me to included services that are assigned to a host group. Currently the only way to create a service group is to use a service directly assigned to a host or another service group. Because most of my checks are added to host groups, which then gets inherited to servers that are assigned to those host groups, I do not see them at all with in service group creation.

I was hoping that service groups would fit this purpose, but they do not seem to work for our configuration. Please let me know if this is something possible for a future release or if there are further questions.

Thanks,
David

dworthcsl

```
Posts: 61
Joined: Wed Jan 11, 2012 3:00 pm
```

**Comment by ericloyd** [comment] 2015-12-09 18:50
Totally agree.  The entire point of service groups is to group services into meaningful groups, right?  (Perhaps that is a tautology...)  So I think any time a service name is used in Nagios, a service group should be just as valid.  Since you can assign services to host groups, there should be no reason why these services, or groups based upon them could not be used elsewhere.

**Comment by hedenface** [comment] 2017-06-18 20:56
Duplicate of #168. Closing. (We'll get to it :) )

**Closed** 2017-06-18 21:49 UTC
Labels: Duplicate, Enhancement
