### ISSUE TITLE
HTML output of plug-ins is parsed in wrong way => webgui unusable

### ISSUE THREAD

**Issue by ggrubert** [NagiosEnterprises/nagioscore#104] opened 2016-01-11 12:05 UTC
Using a plug-in with html output, e.g., check_multi with output option "-r 2", the output of the plug-in is parsed incorrectly. In particular, characters like "<", ">", and "&" are rewritten as html entity. The resulting web page of nagios cannot be represented correctly by web browsers.

See the plug-in and web outputs for nagios 3.5.1 and 4.1.1 attached. In 3.5.1, this bug does not exist.

[nagios-3.5.1-plugin_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/85647/nagios-3.5.1-plugin_output.txt)
[nagios-3.5.1-web_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/85648/nagios-3.5.1-web_output.txt)
[nagios-4.4.1-plugin_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/85649/nagios-4.4.1-plugin_output.txt)
[nagios-4.4.1-web_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/85650/nagios-4.4.1-web_output.txt)

**Comment by jfrickson** [comment] 2016-02-04 18:12
Should be fixed in commit https://github.com/NagiosEnterprises/nagioscore/commit/308e6a31ef93c5a075e5872bcd71ce6914f180d1
on branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

If that fix doesn't solve the problem, please post a message here and I'll reopen it.

**Comment by ggrubert** [comment] 2016-02-05 11:01
Sorry, but this did not solve the problem. Here, the current output of the web GUI

[nagios-4.1.2-Pre1-web_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/118987/nagios-4.1.2-Pre1-web_output.txt)

**Comment by jfrickson** [comment] 2016-02-08 18:06
Can you send the plugin output from that, please?

**Comment by ggrubert** [comment] 2016-02-08 20:09
Sorry that I've changed the test case. Here, the plugin output
[nagios-4.1.2-Pre1-plugin_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/122132/nagios-4.1.2-Pre1-plugin_output.txt)

**Comment by jfrickson** [comment] 2016-02-08 22:10
In your cgi.cfg, did you set escape_html_tags=0?

**Comment by ggrubert** [comment] 2016-02-09 20:54
Of course. Otherwise, there would not be any html interpretation of the plugin output.

**Comment by jfrickson** [comment] 2016-02-09 21:26
I added one additional line

`		else if(('>' == *inwcp) && (FALSE == escape_html_tags)) {

			switch(where_in_tag) {
			case WHERE_IN_TAG_NAME:
			case WHERE_IN_TAG_OUTSIDE_ATTRIBUTE:
			case WHERE_IN_COMMENT:
			case WHERE_IN_TAG_IN_ATTRIBUTE_NAME:               /* THIS ONE IS NEW */
				outstp = copy_wc_to_output(*inwcp, outstp, output_max);
				where_in_tag = WHERE_OUTSIDE_TAG;
				*inwcp = 0;
				break;
`

which might have fixed some of it, but should not have fixed it all. I fed your plugin output into extinfo.cgi and got a good html page out. And I can't find anywhere else where those characters are escaped.

**Comment by ggrubert** [comment] 2016-02-19 13:53
Sorry for my delayed response - I was on holiday. Your modification results in this web output

[nagios-4.1.2-Pre1-web_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/138036/nagios-4.1.2-Pre1-web_output.txt)

That means, e.g., the "ndash" is escaped incorrectly, and the javascript functions do not work.

**Comment by HoppeAndreas** [comment] 2016-05-18 09:56
Hello,

is there any news on that issue ?
I'm trying to set up a new nagios server running core 4.1.1 with check_multi 0.26 and i'm running into the same problem that some of the html entities are not encoded right which breaks the html layout.
The java script in the "Status Information" block has a "&#38;" instead of the "&", and in the image alt tags there are several wrong entites :
"&#62;" instead of ">"
"$#60;" instead of "<"
and "$#38;" instead of "&"
Replacing them in a saved output from the nagios web page fixes the problem

**Comment by ggrubert** [comment] 2016-05-19 12:11
Hello,

I'm sorry. Currently, the issue is still unsolved. Therefore, we are
using nagios 3.5.1 furthermore together with the latest development
version of check_multi.

Best regards,
Gordon

**Comment by jfrickson** [comment] 2016-07-19 21:55
@HoppeAndreas @ggrubert Can either of you put together a shell/perl script that can produce relatively short (like less than 5KB) output that will not encode properly? With the current version of Nagios (4.1.2-RC2), the only problem I can find are entities, like `&ndash`. I'd rather not have to include a table of entity names to loop through. But everything else should be working.

**Comment by HoppeAndreas** [comment] 2016-07-20 11:45
Hello,

i'm currently running this on a 4.1.2-Pre1.
Easy way to reproduce the problem : 

Nagios
>define command {
>  command_name         check_multi
>  command_line         $USER1$/check_multi $ARG1$
>}

>define service {
>	service_description		PingTest
>	use				generic-service
>	host_name			nagios-host
>	check_command			check_multi!-t 60 -T 90 -r 143 -s collapse=0 -f /path/to/ping.cmd
>}

ping.cmd
>command[ test_ping1 ] = check_icmp localhost
>command[ test_ping2 ] = check_icmp localhost
>command[ test_ping3 ] = check_icmp localhost
>command[ test_ping4 ] = check_icmp localhost

Best regards
Andreas

**Comment by jfrickson** [comment] 2016-07-20 14:55
I put in a fix for `&ndash`. One pull request was brought in yesterday with a minor change regarding newlines. Other than those two, cgiutils.c hasn't been changed since Feb 8. My output is attached. The javascript all looks fine.

[nagios-4.1.2-RC2-web_output.txt](https://github.com/NagiosEnterprises/nagioscore/files/373948/nagios-4.1.2-RC2-web_output.txt)

Please try it with the RC2.

**Comment by HoppeAndreas** [comment] 2016-07-21 06:38
i will take a look at it
right now the ndomod is complaining that it was build for revision 402 of the internal object structure and the daemon is running revision 403
Was there a change to the structure ? Or do i need to change that value in ndomod and recompile it ?

**Comment by jfrickson** [comment] 2016-07-21 14:15
It would be best to get the latest ndo (2.1b2), but for now, you can change the value in objects.h and recompile. It was a fairly minor change that won't cause any problems.

**Comment by HoppeAndreas** [comment] 2016-07-25 06:03
i've got everything up and running, looks good to me

**Comment by jfrickson** [comment] 2016-07-28 17:29
Considering this issue closed.

**Closed by jfrickson** 2016-07-28 17:29 UTC
