### ISSUE TITLE
Servicedependencies does not handle servicegroups properly

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#221] opened 2016-09-30 17:44 UTC
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000675](http://tracker.nagios.org/view.php?id=0000675)  - Please follow that link for details.
> Originally reported on 2015-04-01 by  trevorjones

With a dependency config like this, which has many hosts each with several members of the ssh_dependent_services group, i only get the first service on each host actually registered as a dep of SSH_Process

```
define servicedependency{
        service_description SSH_Process
        dependent_servicegroup_name ssh_dependent_services
        inherits_parent 1
        execution_failure_criteria u,c
        }
```

I wrote the following patch that fixes the issue for me.

With this patch I can use servicegroups for one or both of parent and dependent, and it seems to process correctly. I do not know if it will work with all configurations that are valid with the old code, but it fixes a case where it was clearly doing the wrong thing.

**Comment by jfrickson** [comment] 2016-12-13 17:37
We're unable to reproduce the problem. Closing.

**Closed by jfrickson** 2016-12-13 17:37 UTC
Labels: bug, migration
