### ISSUE TITLE
Restricted access user sees additional hosts - when viewing hostgroups

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#216] opened 2016-09-30 17:43 UTC
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000646](http://tracker.nagios.org/view.php?id=0000646)  - Please follow that link for details.

**Comment by jfrickson** [comment] 2016-10-04 18:11
This was a duplicate of tracker issues 519 and 619, both of which were fixed recently.

**Closed by jfrickson** 2016-10-04 18:11 UTC
Labels: duplicate, migration
