### ISSUE TITLE
config files not checked for "valid" email addresses

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#327] opened 2017-02-06 18:00 UTC
An email address without "@" goes through. Obviously, a check for valid in the sense that it is on the mail server doesn't make a lot of sense.

**Comment by ericloyd** [comment] 2017-02-06 18:03
I don't see a problem with this, as the Nagios server may be sending to a local user, which will have its full email address expanded via the local MTA/MDA.  Meaning "root" is a valid email address, which will translate to "root@localhost" by the local mail transfer/delivery agent.  Having an "@" in an email address is not a requirement.

**Comment by rcknag** [comment] 2017-02-09 16:11
I agree with @ericloyd on this one. Contacts may not use an email address that matters, but triggering to an external system, where they could then use the variable for something else.

**Comment by tmcnag** [comment] 2017-02-09 16:14
Seconded (thirded?).  The realm of verifying emails is up to the user.  Slippery Slope argument for sure, but at what point do we argue that Core should also do a `VRFY` against a given address?

**Comment by ericloyd** [comment] 2017-02-09 18:31
Additionally, a contact's email address may not really be an email address if the contact notification is doing something else.  Like in our case, with Twitter (in which case it's a twitter ID) or Pushbullet (in which case it's an API key).

**Comment by box293** [comment] 2017-02-09 22:19
> https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/customobjectvars.html
> Users often request that new variables be added to host, service, and contact definitions. These include variables for SNMP community, MAC address, AIM username, Skype number, and street address. The list is endless. The problem that I see with doing this is that it makes Nagios Core less generic and more infrastructure-specific. Nagios Core was intended to be flexible, which meant things needed to be designed in a generic manner.

I think this is a great statement in the documentation. If you look at a contact definition there is a directive for "pager" and I don't know anyone that uses a pager any more. Perhaps one day "email" will be as useless as "pager" is now.

My point is that validation should not be required on this directive, the other comments provide the reasons why.

**Comment by ericloyd** [comment] 2017-02-09 22:29
Agreed.  All in favor of closing with "works as intended?"

**Comment by jfrickson** [comment] 2017-02-09 22:31
Works as intended. Closing.

**Closed by jfrickson** 2017-02-09 22:31 UTC
