### ISSUE TITLE
Not rescheduling notifications if within excluded timeperiod

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#204] opened 2016-09-30 17:43 UTC
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000527](http://tracker.nagios.org/view.php?id=0000527)  - Please follow that link for details.

**Comment by jfrickson** [comment] 2016-10-05 19:42
This is a duplicate of #196. See that issue for information.

**Closed by jfrickson** 2016-10-05 19:42 UTC
Labels: duplicate, migration
