### ISSUE TITLE
Bug - Quick Search no longer allows search by IP

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#315] opened 2017-01-17 21:55 UTC
Bug - Quick Search no longer allows search by IP

The previous versions of Core supported Quick Search by IP address, validated on Core 4.1.1.

You should be able to search for "127.0.0.1" or "localhost" and localhost should show up.

**Comment by souzarod** [comment] 2017-01-24 16:39
I've same problem after upgrade to version 4.2.4

**Comment by tjyang** [comment] 2017-01-24 18:35
I have both 4.1.1 and 4.2.4 instances and I confirm IP search is not working on 4.2.4.

**Comment by ludmilmm** [comment] 2017-01-24 21:07
I can confirm that the quick search is not working properly in Nagios Core 4.2.4. 

Searching for "127.0.0.1" doesn't produce any results but searching for "localhost" does.

If you had a several hosts, i.e. 192.168.x.1, 192.168.x.2, 192.168.x.3, etc., and you searched by entering "192" in the "Quick Search" bar, you will be presented with only one result - the top host in the list. 

You would notice the same issue if you used a "partial" name. Let's say you have several hosts named vcenter.hostA, vcenter.hostB, vcenter.hostC, etc. If you searched for "vcenter", you would find only vcenter.hostA (the top host in the list). On the other hand, if you searched for "hostA", you would find nothing.

**Comment by jfrickson** [comment] 2017-02-16 17:30
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/da75af039e19372a66cdbcc4c610ff7c20ea76c6

**Closed by jfrickson** 2017-02-16 17:30 UTC
Labels: bug

**Comment by ericloyd** [comment] 2017-02-16 17:33
Finally.  I can start finding my porn servers again.

**Comment by joe1871** [comment] 2017-02-16 23:00
Hey Folks,

Please don't misinterpret my question here as dis-satisfaction.  I love Nagios, and have made a good living in part due to my knowledge of Nagios.  But I have a concern or some confusion about why this wasn't a bigger deal than it seems to have been.  Am I an unusual user in that I search predominantly by IP?  I have > 700 Hosts and > 2500 servicesbeing monitored.  We are much more of an IP based house - host names are there, but we have a pretty well organized set of subnets that make it easy to surmise the IP of a machine.  The question is isn't searching by IP a core need in Nagios?  It is how I move around.  When I found this issue, I had to revert - I couldn't use 4.2.4 because of this.  Did you all just work around this issue, or was it a show stopper for you as well?  I am just curious - I figured an issue of this magnitude would have been caught in testing.  Am I off base about the magnitude?  Just curious.

Second point - or question - can I replace the code in this file or is there a way to get thios fix withoput waiting for another release?  I am sorry - never been through this before.  Is there a mianienance release that incorporates this change, and if so, how do I get it?

Thanks folks - as I said - none of this is bitchin, just not understanding.

Joe

**Comment by box293** [comment] 2017-02-16 23:40
I hear exactly what you are saying, I suppose bugs don't get identified until someone uses the feature and reports it. Nagios has many complexities to it, how do you test every individual feature/function on every release? 

I know when I do a documentation update on installing core+plugins, all I do is install it, check that the default localhost services/plugins work and that I can force an immediate check from the web interface. I wouldn't have checked searching for objects because all that currently exists on a base install is localhost.

I suspect a lot of people don't use the latest release until other have tested it and identified bugs.

Because this has been fixed in the maint branch, you can use git to clone this branch:

```
git clone --recursive -b maint https://github.com/NagiosEnterprises/nagioscore.git
```

Then you will be able to install it normally.

**Comment by jfrickson** [comment] 2017-02-17 14:56
If you don't have git you can:
```
wget https://github.com/NagiosEnterprises/nagioscore/archive/maint.tar.gz
```

**Comment by broxio** [comment] 2017-02-22 03:18
FYI From my system Search by IP in Quick search  is working until version 4.2.1  also the latest release as of today 4.3.0 not include #315 yet , but after patched it working like a charm.
