### ISSUE TITLE
Random (return code 22) on checks after 4.4.0 upgrade

### ISSUE THREAD

**Issue by IronWolve** [NagiosEnterprises/nagioscore#534] opened 2018-06-19 23:41 UTC
I had to roll back.  Upgraded my core 4.3.4 system to latest 4.4.0 today, and checks randomly started getting "Return code 22 out of bounds".   Some checks would just randomly fail and clear.  SSH checks failed more often than others, its check_ssh version 2.2.1 if that helps.

Not sure if there are configurations changes I needed to make for 4.4.0 upgrade, but debugging didn't show why the checks failed.    Did simple troubleshooting and debug, nothing popped out, just error 22s in the log file. 

This was my main nagios system, but I'll clone it and do more debugging, but thought I should at least say something.

**Comment by hedenface** [comment] 2018-06-19 23:54
Yes. Thank you for the information. What operating system? Architecture? How did you perform the upgrade (steps you took)?

**Comment by box293** [comment] 2018-06-20 05:13
Here is a new KB article which provides detailed instructions for upgrading Nagios Core from source:

https://support.nagios.com/kb/article.php?id=797

The important steps are updating the service/daemon files and making sure the `lock_file` directive in `nagios.cfg` matches what the configure script defines.

**Comment by hedenface** [comment] 2018-06-20 10:28
Also, can I see the command definitions themselves? And can you supply the exact error messages?

Thanks.

**Comment by IronWolve** [comment] 2018-06-20 19:40
Centos 7 latest, default Apache.  I normally keep all nagios systems current version of core, so just a normal upgrade with fullinstall,  and no config changes are needed.

I am seeing return codes 22 and a third the amount of 13s on 4.4.0 systems. I see the check_ssh fail the most.

Lock file looks ok
`lock_file=/var/run/nagios.lock`

For the upgrade.  
Did the normal, tar extract, configure, make, full-install.    
The only thing I do differently is install nagios-plugins and symlink the directory, so all my custom plugins are in 1 location for both nrpe/nagios.

libexec -> /usr/lib64/nagios/plugins/
and symlink

I also have pnp4nagios and pagerduty installed.

The definitions are very very simple.

services

```
define service{
        hostgroup_name                  ssh-servers
        service_description             SSH
        check_command                   check_ssh
        use                             service-norm
        notification_interval           0 ; set > 0 if you want to be renotified
        }

```
commands

```
 'check_ssh' command definition
define command{
        command_name    check_ssh
        command_line    /usr/local/nagios/libexec/check_ssh $HOSTADDRESS$
        }

```
hostgroup

```
define hostgroup {
        hostgroup_name  ssh-servers
        alias           SSH servers
        members         server1,server2,server3,etc
        }
```

I run a very simple setup.    command/hostgroup/services to touch for adding systems and checks.

[nagios.txt](https://github.com/NagiosEnterprises/nagioscore/files/2120797/nagios.txt)

**Comment by IronWolve** [comment] 2018-06-20 20:15
Let me check if turning env macros off fixes the issue for me too.

enable_environment_macros=0

**Comment by hedenface** [comment] 2018-06-20 20:39
There is also a recent push 
https://github.com/NagiosEnterprises/nagioscore/commit/11901bc17f897075d3b111c23335a2ca8c1b8229

That I believe contains the fix.

**Comment by hedenface** [comment] 2018-06-20 20:49
Closing this, as I believe the fix is in that commit. If not, please re-open the issue.

**Closed by hedenface** 2018-06-20 20:49 UTC

**Comment by sshmanko** [comment] 2018-06-21 07:55
@hedenface We still experience code 22 if *enable_environment_macros* set to *1*
No such messages if `enable_environment_macros=0`
Using head from **maint** branch

**Comment by hedenface** [comment] 2018-06-21 10:16
@sshmanko  I'd like some log entries if possible. I am unable to reproduce as of yet.

**Comment by sshmanko** [comment] 2018-06-21 11:18
@hedenface sorry, all good here, my bad
