### ISSUE TITLE
Changing map layout duplicates hosts shown in map

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nagioscore#471] opened 2018-01-29 21:46 UTC
Originally reported here:
https://support.nagios.com/forum/viewtopic.php?t=47296

> When I go to the map in the webinterface and select another layout (e.g. from Balanced Tree (Horizontal) to Circular Markup), suddenly every host is shown twice. When I just hit the map-link in the navigation everything is fine once again - at least as long as I don't chang the layout.

I have confirmed this behavior was also present in 4.3.3

I'm not 100% sure but I believe one of the JSON calls is adding to the objects instead of overwriting them.

**Comment by hedenface** [comment] 2018-02-15 14:33
Adding to 4.4 tentatively, it will likely get pushed back farther - just want to keep it on the radar. Thanks!

**Comment by hedenface** [comment] 2018-05-31 21:54
So - definitely reproduced.

If you drop the two js files: `nagios-decoration.js` and `map-directive.js` from nagios-4.2.2 into the `/usr/local/nagios/share/js/` directory, the problem goes away. The diffs of these files aren't much - so I'm going through change by change to determine the cause. This should be fixed shortly.

**Comment by hedenface** [comment] 2018-06-01 13:28
The original code when it was working was:

```
if (!node.hasOwnProperty("chlidren") || node.children == null) {
	node.children = new Array;
}
```

Since there was no property chlidren (should be children), it always set `node.children` as a `new Array`.
But when the spelling was fixed, it actually needed `node.children == null` to be true - which it never was (when SWITCHING).

So I think the appropriate fix is:

```
if (node.hasOwnProperty("children")) {
    node.children = new Array;
}
```

This mimics the behavior from when it was working. I'm by no means an angular expert though, so if anyone out there wanted to review my code - please feel free.

**Comment by hedenface** [comment] 2018-06-19 15:33
Was not adequately fixed at mentioned commit.

**Comment by jomann09** [comment] 2019-01-07 06:11
This should be fixed in maint branch now, should be out in 4.4.3

**Closed by jomann09** 2019-01-07 06:11 UTC
Labels: Bug

**Comment by marcoafmagalhaes** [comment] 2023-02-07 19:37
Guys.... The solution above in fact solve this problem for you? 
If so, what have you done? I already changed the code mentioned in a million ways....

**Comment by sawolf** [comment] 2023-02-13 21:06
Hi @marcoafmagalhaes - all of the people above were employees of Nagios Enterprises and also no longer work for the company. If you're running into the same problem on an older version of Nagios Core, I would recommend updating to the most recent version. If you don't want to do that, you can look at https://github.com/NagiosEnterprises/nagioscore/commit/b21e80c04f150141e022ffa749aa921f42114eb8 for the most recent patch that Jake added before closing this issue.

If you are still running into this or a similar issue on a recent version of Nagios Core, feel free to create a new issue.
