### ISSUE TITLE
Nagios process memory leak on HUP

### ISSUE THREAD

**Issue by danbf** [NagiosEnterprises/nagioscore#608] opened 2019-01-10 17:17 UTC
we are seeing a memory leak on a `HUP` issued to the nagios process on nagios-4.4.2 and nagios-4.4.3rc1

we run nagios under runit and issue a `sv hup /etc/sv/nagios` to hup nagios for updates to our config file.  with each hup our memory increases by about 1-3MB depending on how large the config file is.

**Comment by jomann09** [comment] 2019-01-10 18:45
This might be related to issue #573 but I am not sure. Will have to look into it further.

**Comment by danbf** [comment] 2019-01-10 18:54
this seems as though it may have been in place since nagios-4.1.1.  we dynamically update our config and so hup nagios frequently

**Comment by danbf** [comment] 2019-01-10 21:05
we observed this most recently running in the python3.7 docker container;
https://github.com/docker-library/python/blob/master/3.7/stretch/Dockerfile

**Comment by danbf** [comment] 2019-01-11 21:16
running this hup on nagios:
```
#!/bin/bash
while :
do
    echo "Press [CTRL+C] to stop.."
    sv hup /etc/sv/nagios
    sleep 1
done
```

results in a sharp reproducible leak of memory:
![screen shot 2019-01-11 at 4 15 01 pm](https://user-images.githubusercontent.com/5041307/51060026-23ca3480-15bc-11e9-9430-9eec793a9ab5.png)

**Comment by jomann09** [comment] 2019-01-14 16:46
Can you test this using the new maint branch commits?

**Comment by jomann09** [comment] 2019-01-14 18:24
Going to close this as a duplicate of #573 which is fixed in the maint branch and will be in 4.4.3

**Closed by jomann09** 2019-01-14 18:24 UTC
Labels: Bug, Duplicate

**Comment by danbf** [comment] 2019-01-14 21:19
patch looks solid.  `hup`ing is not longer leaking mem.

![screen shot 2019-01-14 at 4 18 21 pm](https://user-images.githubusercontent.com/5041307/51141767-1c06cc00-1818-11e9-8529-b3d113861409.png)

**Comment by danbf** [comment] 2019-01-15 15:03
👍 thanks much for hitting this so quickly.
