### ISSUE TITLE
Error upgrade to 4.3.4

### ISSUE THREAD

**Issue by Raptus1** [NagiosEnterprises/nagioscore#437] opened 2017-10-10 17:25 UTC
On upgrading to 4.3.4 from 4.2.4 I get the following error:

    Oct 10 15:17:50 systemd[1]: Starting LSB: Starts and stops the Nagios monitoring server...
    Oct 10 15:17:50 su[28095]: Successful su for nagios by root
    Oct 10 15:17:50 su[28095]: + ??? root:nagios
    Oct 10 15:17:50 su[28095]: pam_unix(su:session): session opened for user nagios by (uid=0)
    Oct 10 15:17:50 nagios[28089]: Starting nagios:ERROR: Could not create or update '/usr/local/nagios/var/nagios.configtest'
    Oct 10 15:17:50 systemd[1]: nagios.service: Control process exited, code=exited status=8
    Oct 10 15:17:50 systemd[1]: Failed to start LSB: Starts and stops the Nagios monitoring server.
    Oct 10 15:17:50 systemd[1]: nagios.service: Unit entered failed state.
    Oct 10 15:17:50 systemd[1]: nagios.service: Failed with result 'exit-code'.

It worked fine before upgrading to 4.3.4 and upgrading to 4.3.2 instead also works fine.

I have not tried from 4.3.2 to 4.3.4, but I don't think it will be any different.

**Comment by box293** [comment] 2017-10-10 23:29
What operating system are you running on?

**Comment by Raptus1** [comment] 2017-10-11 01:05
Ubuntu 16.04                                                                                                                                                                                                                                                                                                                 From: notifications@github.comSent: October 11, 2017 1:29 AMTo: nagioscore@noreply.github.comReply-to: reply@reply.github.comCc: Lars.Ihler@gmail.com; author@noreply.github.comSubject: Re: [NagiosEnterprises/nagioscore] Error upgrade to 4.3.4 (#437)  What operating system are you running on?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hedenface** [comment] 2017-10-24 12:46
There is some kind of issue going on all over the place with the configtest file. You should be able to disable the option in your startup script and it will be fine. This will be fixed shortly though.

**Comment by greenlogles** [comment] 2017-12-05 16:22
Hi

The same problem is on SLES 12.2. After upgrade from 4.3.2 to 4.3.4 stop/restart commands work incorrect. Looks like it doesn't do anything :(

**Comment by hedenface** [comment] 2017-12-05 18:23
Did you use the new init script by chance @greenlogles ?

**Comment by greenlogles** [comment] 2017-12-07 16:09
@hedenface I've tried script from 4.4.0-alpha branch, but it also doesn't work correctly. It starts nagios, but can't stop.

Also this version contains some bug: nagios init script contains default nagios user. I use next confugeation:

`./configure  --prefix=/opt/nagios --with-command-user=pmpnagios --with-command-group=pmpnagios -with--nagios-user=pmpnagios --with-nagios-group=pmpnagios`

Result:

` egrep "^NagiosUser|^NagiosGroup" daemon-init`
`NagiosUser=nagios`
`NagiosGroup=pmpnagios`

**Comment by hedenface** [comment] 2017-12-07 17:19
I haven't done any work on the 4.4.0 - I meant when you were upgrading nagios, did you also upgrade the init script with:

`make install-init`

?

**Comment by greenlogles** [comment] 2017-12-07 17:23
@hedenface yes, sure. I did.
I've updated manually NagiosUser name.
Is it possible to create systemd unit file for nagios ? I hope it can resolve many problems on systemd systems

**Comment by hedenface** [comment] 2017-12-07 17:44
The systemd unit file will be in 4.4.0 :)

**Comment by hedenface** [comment] 2017-12-07 21:45
Here is a service file if you'd like to have a try: 
https://github.com/NagiosEnterprises/nagioscore/commit/324aa1aafb78c930f567718096bdb6725254db89

**Comment by hedenface** [comment] 2017-12-29 20:36
I actually updated it just recently in https://github.com/NagiosEnterprises/nagioscore/commit/c8dc0863ce760e1e7d13826cab1bc57cfd5268a3

**Comment by hedenface** [comment] 2017-12-29 20:46
> Also this version contains some bug: nagios init script contains default nagios user.

You're only using one dash (`-`) in front of `nagios-user=`

**Comment by hedenface** [comment] 2017-12-29 20:55
@box293 's KB Article here: https://support.nagios.com/kb/article/nagios-core-error-could-not-create-or-update-nagios-configtest-760.html should do a good job explaining the configtest issue. I'm closing this issue, as the systemd service file has been added, and the `--nagios-user=` was resolved (tested and confirmed).

To summarize: make sure your nagios user has a proper shell.

**Closed by hedenface** 2017-12-29 20:55 UTC
Labels: Bug, Priority
