### ISSUE TITLE
Status Map does not draw loops.

### ISSUE THREAD

**Issue by ParthKolekar** [NagiosEnterprises/nagioscore#347] opened 2017-03-14 15:30 UTC
I have a switch on the network, that is connected to the core L3 via two routes. One primary and one built for redundancy. 

The STP takes care of network loops, but I'd still like to show the connected edge on the network. What happens instead is that when I add two parents to a switch, it makes a separate link for both. 

Is this possible to be remedied?

**Comment by ParthKolekar** [comment] 2017-03-14 15:32
I am talking about the newer HTML status map in Nagios 4.

**Comment by ParthKolekar** [comment] 2017-03-14 15:32
The old CGI Map draws it just fine.

**Comment by jfrickson** [comment] 2017-03-14 17:37
See issue #34 
D3 doesn't support multiple parents. At least it didn't the last time I did the research. I'll check again.

**Comment by ParthKolekar** [comment] 2017-03-14 17:39
That's cool, thanks for the heads up.

**Comment by ParthKolekar** [comment] 2017-03-14 17:47
Since we run the CentOS 7 epel version, this is going to take a while for me anyway.

**Comment by hedenface** [comment] 2017-06-18 18:41
I'm closing this issue since it's open in several other places. We **will** get a fix for this - hopefully in Core 5. Stay tuned!

**Closed by hedenface** 2017-06-18 18:41 UTC
Labels: Bug, Duplicate

**Comment by nuno-silva** [comment] 2018-05-15 14:35
@hedenface I found three closed ("duplicate") issues about this problem saying it will be fixed in Core 5. However, I couldn't find an open issue where the problem is scheduled to be fixed.
Has this been fixed yet? Is there a workaround for this?

PS: sorry for bringing up a closed issue.

**Comment by hedenface** [comment] 2018-05-25 10:06
We have a few ways of tracking what's going on with Core. Only one of them is GitHub issues - we also have an internal tracker for enhancements/bug fixes. A lot of times those get transferred to GitHub, but sometimes they don't. This is just "one of those things" that we know we need to do.

That said, if you'd like to open an issue [that I won't close] referencing all of those issues, that would probably keep it in the public's eye a bit better :)

**Comment by nuno-silva** [comment] 2018-05-25 10:36
@hedenface thanks for your reply. I'll go ahead and do that.
